In [1]:
import pandas as pd
import numpy as np

In [4]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600], 
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [5]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [6]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [7]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [8]:
df_s.shape

(3, 3)

In [11]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [9]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [10]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [12]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [13]:
df_s["v1"]

0    100
1    200
2    300
Name: v1, dtype: int64

In [14]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [15]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [16]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [17]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [18]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [19]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [20]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [22]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [24]:
df_s["shape"].isin(["A", "C"])

0     True
1    False
2     True
Name: shape, dtype: bool

In [23]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [25]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [26]:
df_s.columns

Index(['v1', 'v2', 'shape'], dtype='str')

In [27]:
df_s.columns[1]

'v2'

In [29]:
df_s.columns[1:]

Index(['v2', 'shape'], dtype='str')

In [30]:
df_s.columns.to_list()

['v1', 'v2', 'shape']

In [33]:
df_s2 = df_s.rename(columns = {"v1": "col1"})
df_s2

   col1   v2 shape
0   100  400     A
1   200  500     B
2   300  600     C

In [34]:
df_s3 = df_s2.add_suffix("_nor")
df_s3

   col1_nor  v2_nor shape_nor
0       100     400         A
1       200     500         B
2       300     600         C

In [36]:
df_s["v1"]

0    100
1    200
2    300
Name: v1, dtype: int64