### 교육 중에 작성하는 코드는 나중에 전부 공유드립니다.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [3]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [4]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [5]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [6]:
df_s.shape

(3, 3)

In [7]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [8]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [9]:
df_s.drop(columns = "shape")

    v1   v2
0  100  400
1  200  500
2  300  600

In [10]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [11]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [12]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [13]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [14]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [15]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [16]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [17]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [18]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [19]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [20]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [21]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [22]:
df_s2 = df_s.rename(columns = {"v1": "new"})
df_s2 = df_s2.add_suffix("_nor")
df_s2

   new_nor  v2_nor shape_nor
0      100     400         A
1      200     500         B
2      300     600         C

In [23]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
1,KTOP 30,11520.28,-86.30,-0.74,11609.44,11702.14,11490.84,50048566,5645660149606,1208343758559140,20210503

In [24]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
29,KRX 300,1916.40,15.35,0.81,1903.57,1916.40,1892.36,244040965,11708937073166,2043945386926060,20210504
58,KRX 300,1927.40,11.00,0.57,1916.50,1927.40,1904.76,341534594,13004811637843,2059578026871265,20210506
87,KRX 300,1936.40,9.00,0.47,1926.59,1942.80,1925.24,253210064,11101387594368,2070880919861705,20210507
116,KRX 300,1968.47,32.07,1.66,1938.63,1973.17,1938.63,294421965,13784089230905,2105851479694870,20210510
145,KRX 300,1936.37,-32.10,-1.63,1962.35,1962.35,1929.74,339313903,15976844135869,2075382637364310,20210511
174,KRX 300,1903.99,-32.38,-1.67,1936.18,1936.82,1891.55,352799341,17136393156387,2043316163563660,20210512
203,KRX 300,1878.46,-25.53,-1.34,1893.72,1899.65,1869.37,402046342,16819555547844,2014899605250130,20210513
232,KRX 300,1899.13,20.67,1.10,1884.85,1905.26,1884.85,229722051,11413338490975,2038805937109210,20210514
261,KRX 300,1891.72,-7.41,-0.39,1906.35,1912.03,1882.03,258826078,11333749894174,2027913472817160,20210517
290,KRX 300,1913.67,21.95,1.16,1892.13,1917.43,1892.13,248484463,11503457331908,2053066878361790,20210518
319,KRX 300,1906.26,-7.41,-0.39,1914.61,1914.61,1894.97,224240546,10906767355146,2047273506168110,20210520
348,KRX 300,1907.38,1.12,0.06,1912.44,1932.91,1902.03,247944350,12200080796814,2042477090377600,20210521
377,KRX 300,1897.69,-9.69,-0.51,1906.60,1910.68,1893.57,210439901,9568918143070,2035955475360540,20210524
406,KRX 300,1915.26,17.57,0.93,1903.17,1916.85,1900.82,208362193,9591985036024,2054548999380540,20210525
435,KRX 300,1911.68,-3.58,-0.19,1915.76,1922.77,1907.37,257307289,10837464472787,2051152192863740,20210526
464,KRX 300,1910.09,-1.59,-0.08,1913.55,1915.55,1894.84,327607567,17156385452981,2043966667110420,20210527
493,KRX 300,1922.87,12.78,0.67,1913.77,1929.84,1912.48,234219802,10813228145679,2058019926179550,20210528
522,KRX 300,1932.64,9.77,0.51,1924.63,1933.75,1916.75,278319769,11293303810625,2068979877957040,20210531

In [25]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [26]:
df["종가"].idxmax()

117

In [27]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]] # Series

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [28]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]] # DataFrame

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [29]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [30]:
df_sub.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  5 non-null      float64
 1   Sepal.Width   4 non-null      float64
 2   Petal.Length  4 non-null      float64
 3   Petal.Width   5 non-null      float64
 4   Species       5 non-null      str
dtypes: float64(4), str(1)
memory usage: 332.0 bytes

In [31]:
df_sub.dtypes # 중요!!

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species             str
dtype: object

In [32]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [33]:
df_sub.isna()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0         False         True          True        False    False
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False

In [34]:
df_sub.isna().sum()

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [35]:
df_sub.isna().sum(axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [36]:
df_sub.isna().apply(lambda x: x.sum(), axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [37]:
df_sub.apply(lambda x: x.isna().sum(), axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [38]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [39]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [41]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
df_sub2 = df.tail()
df_sub2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           NaN          2.5           NaN          NaN  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

In [43]:
df_sub3 = df_sub2.reset_index()
df_sub4 = df_sub2.reset_index(drop = True)

In [44]:
df_sub3

   index  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0    145           6.7          3.0           5.2          2.3  virginica
1    146           NaN          2.5           NaN          NaN  virginica
2    147           6.5          3.0           5.2          2.0  virginica
3    148           6.2          3.4           5.4          2.3  virginica
4    149           5.9          3.0           5.1          NaN  virginica

In [45]:
df_sub4

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0           6.7          3.0           5.2          2.3  virginica
1           NaN          2.5           NaN          NaN  virginica
2           6.5          3.0           5.2          2.0  virginica
3           6.2          3.4           5.4          2.3  virginica
4           5.9          3.0           5.1          NaN  virginica

* 결측값 처리: https://datadoctorblog.com/2023/04/24/Py-Basic-Pandas-Missing/
* 정렬: https://datadoctorblog.com/2023/04/25/Py-Basic-Pandas-Sorting/
* 원소/조합 세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/

In [46]:
df = pd.read_csv("bike.csv")
df.head(2)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40

In [47]:
df["season"].unique()

array([1, 2, 3, 4])

In [48]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [49]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [50]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [51]:
df[["season", "holiday"]].drop_duplicates()

      season  holiday
0          1        0
372        1        1
1323       2        0
1658       2        1
2690       3        0
2762       3        1
4055       4        0
4271       4        1

In [52]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [53]:
df_sub1 = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_sub1)

2615

In [54]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

In [55]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [56]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

In [57]:
df_sub2.reset_index().sort_index()

   index  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0    145           6.7          3.0           5.2          2.3  virginica
1    146           NaN          2.5           NaN          NaN  virginica
2    147           6.5          3.0           5.2          2.0  virginica
3    148           6.2          3.4           5.4          2.3  virginica
4    149           5.9          3.0           5.1          NaN  virginica

In [58]:
df_sub2.sort_index().reset_index()

   index  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0    145           6.7          3.0           5.2          2.3  virginica
1    146           NaN          2.5           NaN          NaN  virginica
2    147           6.5          3.0           5.2          2.0  virginica
3    148           6.2          3.4           5.4          2.3  virginica
4    149           5.9          3.0           5.1          NaN  virginica

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [59]:
df = pd.read_csv("diamonds.csv")
df.head(1)

   carat    cut color clarity  depth  table  price     x     y     z
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

In [60]:
df.groupby("cut")["price"].max()

cut
Fair         18574
Good         18788
Ideal        18806
Premium      18823
Very Good    18818
Name: price, dtype: int64

In [61]:
x = df.loc[df["cut"] == "Fair", "price"]
x.max()

np.int64(18574)

In [62]:
df.groupby("cut")[["price", "x"]].max()

           price      x
cut
Fair       18574  10.74
Good       18788   9.44
Ideal      18806   9.65
Premium    18823  10.14
Very Good  18818  10.01

In [63]:
ser_g1 = df.groupby(["cut", "color"])["price"].max()
ser_g1.head()

cut   color
Fair  D        16386
      E        15584
      F        17995
      G        18574
      H        18565
Name: price, dtype: int64

In [64]:
df_g1 = df.groupby(["cut", "color"])[["price", "x"]].max()
df_g1.head()

            price      x
cut  color
Fair D      16386   9.42
     E      15584   8.16
     F      17995   8.58
     G      18574   8.75
     H      18565  10.00

In [65]:
df_g2 = df.groupby("cut")["price"].max().reset_index()
df_g2

         cut  price
0       Fair  18574
1       Good  18788
2      Ideal  18806
3    Premium  18823
4  Very Good  18818

In [66]:
df_g3 = df.groupby("cut")["price"].agg(["min", "max"]).reset_index()
df_g3

         cut  min    max
0       Fair  337  18574
1       Good  327  18788
2      Ideal  326  18806
3    Premium  326  18823
4  Very Good  336  18818

In [67]:
df_g4 = df.groupby("cut")[["price", "x"]].agg({"price": "min", "x": "max"}).reset_index() # 기출유형 🎯
df_g4

         cut  price      x
0       Fair    337  10.74
1       Good    327   9.44
2      Ideal    326   9.65
3    Premium    326  10.14
4  Very Good    336  10.01

In [70]:
df["count"] = 1
df_g5 = df.groupby(["cut", "color"])["count"].sum().reset_index()
df_g5.head()

    cut color  count
0  Fair     D    163
1  Fair     E    224
2  Fair     F    312
3  Fair     G    314
4  Fair     H    303

* 문자 데이터: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [ ]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

In [73]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [74]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [75]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

0    abc
1      🔥
2      🩵
Name: v2, dtype: str

In [76]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [77]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [78]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [79]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [81]:
df_tx.loc[df_tx["v2"].str.contains("a"), ]

    v1   v2         v3
0  100  abc        123
1  200  aaa  1234-5678

In [82]:
df_tx.loc[~df_tx["v2"].str.contains("a"), ]

    v1   v2             v3
2  300  ccc  010-1234-5678

In [ ]:
df_tx["v2"].str.contains("a")

In [ ]:
# pd.Series.str.contains()

In [ ]:
print(df_tx["v2"].str.contains.__doc__) # 언더바 2개!
# 특정 함수/메서드/클래스 뒤의 괄호 대신 __doc__ 를 쓴 다음 전체를 print() 로 감싸면
# 내부 문서를 출력할 수 있음.
# [Shift] + [Tab]이 먹히지 않을 때 유용함.
# 해당 문서는 각 라이브러리의 공식문서와 같음.

In [91]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [87]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"][0]

'123'

In [92]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [93]:
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: str

In [95]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4

      0     1     2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [96]:
df_tx_v4[0]

0     123
1    1234
2     010
Name: 0, dtype: str

In [ ]:
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_2

In [ ]:
df_tx_v4_3 = df_tx_v4_2.fillna("🛫")
df_tx_v4_3

* 시간데이터: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [102]:
ser_t1 = pd.Series(["2026-06-10", "2026-06-11", "2026-06-12"])
ser_t2 = pd.Series(["2026년 06월 10일", "2026년 06월 11일", "2026년 06월 12일"])
ser_t3 = pd.Series([20260610, 20260611, 20260612])
ser_t4 = pd.Series([1234, 2345, 3456])

In [103]:
pd.to_datetime(ser_t1)

0   2026-06-10
1   2026-06-11
2   2026-06-12
dtype: datetime64[us]

In [106]:
# pd.to_datetime(ser_t2) # 에러

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [110]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일") # 대소문자 구분 잘해야 함.

0   2026-06-10
1   2026-06-11
2   2026-06-12
dtype: datetime64[us]

In [111]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020260610
1   1970-01-01 00:00:00.020260611
2   1970-01-01 00:00:00.020260612
dtype: datetime64[ns]

In [113]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-06-10
1   2026-06-11
2   2026-06-12
dtype: datetime64[us]

In [114]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [115]:
pd.to_datetime(ser_t4, origin = "2026-06-10", unit = "D")

0   2029-10-26
1   2032-11-10
2   2035-11-26
dtype: datetime64[s]

In [129]:
df = pd.read_csv("bike.csv")
df.head(1)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16

In [130]:
df_dt2 = df[["datetime"]].copy() 
# 특히 시험버전의 Pandas의 경우 깊은 복사가 아닌 얕은 복사로
# 동작하는 경우가 많기 때문에 간간히 .copy() 를 사용하는 것을 권장.

In [131]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday # 토요일: 5, 일요일: 6
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0) # 주말 1, 주중 0
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [ ]:
df_dt2.head(2)

In [133]:
df_dt = pd.DataFrame(dict(date = ["2026-06-10", "2026-06-11", "2026-06-12"]))
df_dt["origin"] = "2026-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2026-06-10 2026-01-01 160 days     160
1 2026-06-11 2026-01-01 161 days     161
2 2026-06-12 2026-01-01 162 days     162

In [139]:
# df_dt["diff"] + 20
# df_dt["diff"] * 2

In [142]:
# date_range() 는 굳이 몰라도 됨,,,
df_t = pd.DataFrame(dict(date = pd.date_range("2026-06-01", "2026-06-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))
df_t

        date      v
0 2026-06-01  100.0
1 2026-06-02  200.0
2 2026-06-03  300.0
3 2026-06-04    NaN
4 2026-06-05  500.0
5 2026-06-06  600.0
6 2026-06-07  700.0

In [143]:
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_s2"] = df_t["v"].shift(2)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(), 
                          (df_t["v_s1"] + df_t["v_sn1"]) / 2, 
                          df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate() # 기본 동작은 선형보간.
df_t

        date      v   v_s1   v_s2  v_sn1  v_fill_1  v_fill_2
0 2026-06-01  100.0    NaN    NaN  200.0     100.0     100.0
1 2026-06-02  200.0  100.0    NaN  300.0     200.0     200.0
2 2026-06-03  300.0  200.0  100.0    NaN     300.0     300.0
3 2026-06-04    NaN  300.0  200.0  500.0     400.0     400.0
4 2026-06-05  500.0    NaN  300.0  600.0     500.0     500.0
5 2026-06-06  600.0  500.0    NaN  700.0     600.0     600.0
6 2026-06-07  700.0  600.0  500.0    NaN     700.0     700.0

In [ ]:
df_e = pd.read_csv("elec_load_2017_7d.csv")
df_e.head(1)

In [149]:
df_m1 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head(2)

   YEAR  MONTH  DAY variable  value
0  2017      1    1     X1HR  60178
1  2017      1    2     X1HR  57067

In [150]:
df_m2 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"], 
                  var_name = "HOUR", value_name = "LOAD")
df_m2.head(2)

   YEAR  MONTH  DAY  HOUR   LOAD
0  2017      1    1  X1HR  60178
1  2017      1    2  X1HR  57067

In [147]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지
# regex: regular expression(정규 표현식), 고급 텍스트 처리를 위한 별도의 문법

In [148]:
df_m2.head(2)

   YEAR  MONTH  DAY  HOUR   LOAD h1 h2 h3 h4
0  2017      1    1  X1HR  60178  1  1  1  1
1  2017      1    2  X1HR  57067  1  1  1  1

In [151]:
df_bike = pd.read_csv("bike.csv")
df_b1 = df_bike.iloc[:4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8]

In [ ]:
df_b1

In [ ]:
df_b2

In [ ]:
# pd.concat(df_b1, df_b2)
pd.concat([df_b1, df_b2])

In [160]:
pd.concat([df_b1, df_b2], axis = 1)

   weather  temp   atemp  temp   atemp  humidity
0      1.0  9.84  14.395   NaN     NaN       NaN
1      1.0  9.02  13.635  9.02  13.635      80.0
2      1.0  9.02  13.635  9.02  13.635      80.0
3      1.0  9.84  14.395  9.84  14.395      75.0
4      NaN   NaN     NaN  9.84  14.395      75.0

In [161]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)

   weather  temp   atemp  temp_y  atemp_y  humidity_y
0        1  9.84  14.395    9.02   13.635          80
1        1  9.02  13.635    9.02   13.635          80
2        1  9.02  13.635    9.84   14.395          75
3        1  9.84  14.395    9.84   14.395          75