In [109]:
import pandas as pd
import numpy as np

In [110]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600], 
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [111]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [112]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [113]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [114]:
df_s.shape

(3, 3)

In [115]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [116]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [117]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [118]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [119]:
df_s["v1"]

0    100
1    200
2    300
Name: v1, dtype: int64

In [120]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [121]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [122]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [123]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [124]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [125]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [126]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [127]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [128]:
df_s["shape"].isin(["A", "C"])

0     True
1    False
2     True
Name: shape, dtype: bool

In [129]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [130]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [131]:
df_s.columns

Index(['v1', 'v2', 'shape'], dtype='str')

In [132]:
df_s.columns[1]

'v2'

In [133]:
df_s.columns[1:]

Index(['v2', 'shape'], dtype='str')

In [134]:
df_s.columns.to_list()

['v1', 'v2', 'shape']

In [135]:
df_s2 = df_s.rename(columns = {"v1": "col1"})
df_s2

   col1   v2 shape
0   100  400     A
1   200  500     B
2   300  600     C

In [136]:
df_s3 = df_s2.add_suffix("_nor")
df_s3

   col1_nor  v2_nor shape_nor
0       100     400         A
1       200     500         B
2       300     600         C

In [137]:
df_s["v1"]

0    100
1    200
2    300
Name: v1, dtype: int64

In [138]:
import os
os.listdir() # 여기 출력 결과에서 .csv 파일이 많이 보여야 함.

['.ipynb_checkpoints',
 '01_DX_Class_Data_Set.zip',
 '02_Test_Data_Set',
 '03_crawling',
 'bike.csv',
 'classification_data_01.csv',
 'class_261028.ipynb',
 'class_261028_0934.ipynb',
 'class_261028_0949.ipynb',
 'diabetes.csv',
 'diamonds.csv',
 'edu_enrollees.csv',
 'elec_load_2017_7d.csv',
 'install_libraries.ipynb',
 'iris.csv',
 'iris_missing.csv',
 'krx_202105_cp949.csv',
 'krx_202105_utf8.csv',
 'linear_regression_01.csv',
 'linear_regression_analysis.ipynb',
 'logistic_regression_01.csv',
 'packages',
 'preprocessing_weekday_count.ipynb',
 'prj',
 'Python_313용_파일',
 'Python_37용_파일',
 'python_lv2_설치파일.zip',
 'Python_Preprocessing_remove_extreme_values_groupby.ipynb',
 'qqplot.ipynb',
 'sales.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [139]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
1,KTOP 30,11520.28,-86.30,-0.74,11609.44,11702.14,11490.84,50048566,5645660149606,1208343758559140,20210503

In [140]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
29,KRX 300,1916.40,15.35,0.81,1903.57,1916.40,1892.36,244040965,11708937073166,2043945386926060,20210504
58,KRX 300,1927.40,11.00,0.57,1916.50,1927.40,1904.76,341534594,13004811637843,2059578026871265,20210506
87,KRX 300,1936.40,9.00,0.47,1926.59,1942.80,1925.24,253210064,11101387594368,2070880919861705,20210507
116,KRX 300,1968.47,32.07,1.66,1938.63,1973.17,1938.63,294421965,13784089230905,2105851479694870,20210510
145,KRX 300,1936.37,-32.10,-1.63,1962.35,1962.35,1929.74,339313903,15976844135869,2075382637364310,20210511
174,KRX 300,1903.99,-32.38,-1.67,1936.18,1936.82,1891.55,352799341,17136393156387,2043316163563660,20210512
203,KRX 300,1878.46,-25.53,-1.34,1893.72,1899.65,1869.37,402046342,16819555547844,2014899605250130,20210513
232,KRX 300,1899.13,20.67,1.10,1884.85,1905.26,1884.85,229722051,11413338490975,2038805937109210,20210514
261,KRX 300,1891.72,-7.41,-0.39,1906.35,1912.03,1882.03,258826078,11333749894174,2027913472817160,20210517
290,KRX 300,1913.67,21.95,1.16,1892.13,1917.43,1892.13,248484463,11503457331908,2053066878361790,20210518
319,KRX 300,1906.26,-7.41,-0.39,1914.61,1914.61,1894.97,224240546,10906767355146,2047273506168110,20210520
348,KRX 300,1907.38,1.12,0.06,1912.44,1932.91,1902.03,247944350,12200080796814,2042477090377600,20210521
377,KRX 300,1897.69,-9.69,-0.51,1906.60,1910.68,1893.57,210439901,9568918143070,2035955475360540,20210524
406,KRX 300,1915.26,17.57,0.93,1903.17,1916.85,1900.82,208362193,9591985036024,2054548999380540,20210525
435,KRX 300,1911.68,-3.58,-0.19,1915.76,1922.77,1907.37,257307289,10837464472787,2051152192863740,20210526
464,KRX 300,1910.09,-1.59,-0.08,1913.55,1915.55,1894.84,327607567,17156385452981,2043966667110420,20210527
493,KRX 300,1922.87,12.78,0.67,1913.77,1929.84,1912.48,234219802,10813228145679,2058019926179550,20210528
522,KRX 300,1932.64,9.77,0.51,1924.63,1933.75,1916.75,278319769,11293303810625,2068979877957040,20210531

In [141]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [142]:
df["종가"].idxmax()

117

In [143]:
df.loc[117, ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [144]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [145]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [146]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
len(df_sub)

5

In [147]:
df_sub.shape

(5, 5)

In [148]:
df_sub.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  5 non-null      float64
 1   Sepal.Width   4 non-null      float64
 2   Petal.Length  4 non-null      float64
 3   Petal.Width   5 non-null      float64
 4   Species       5 non-null      str
dtypes: float64(4), str(1)
memory usage: 332.0 bytes

In [149]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [150]:
df_sub.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species             str
dtype: object

In [151]:
df_sub.isna()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0         False         True          True        False    False
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False

In [152]:
df_sub.isna().sum() # ⭐⭐⭐

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [153]:
df_sub.isna().sum(axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [154]:
df_sub["Sepal.Width"].isna()

0     True
1    False
2    False
3    False
4    False
Name: Sepal.Width, dtype: bool

In [155]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [156]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [157]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [158]:
df_sub["Sepal.Width"].fillna(-999)

0   -999.0
1      3.0
2      3.2
3      3.1
4      3.6
Name: Sepal.Width, dtype: float64

In [159]:
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [160]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [161]:
df_sub.index.to_list()

[0, 1, 2, 3, 4]

In [162]:
df_sub2 = df.tail()
df_sub2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           NaN          2.5           NaN          NaN  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

In [163]:
df_sub3 = df_sub2.reset_index()
df_sub3

   index  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0    145           6.7          3.0           5.2          2.3  virginica
1    146           NaN          2.5           NaN          NaN  virginica
2    147           6.5          3.0           5.2          2.0  virginica
3    148           6.2          3.4           5.4          2.3  virginica
4    149           5.9          3.0           5.1          NaN  virginica

In [164]:
df_sub4 = df_sub2.reset_index(drop = True)
df_sub4

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0           6.7          3.0           5.2          2.3  virginica
1           NaN          2.5           NaN          NaN  virginica
2           6.5          3.0           5.2          2.0  virginica
3           6.2          3.4           5.4          2.3  virginica
4           5.9          3.0           5.1          NaN  virginica

* 결측처리: https://datadoctorblog.com/2023/04/24/Py-Basic-Pandas-Missing/
* 정렬: https://datadoctorblog.com/2023/04/25/Py-Basic-Pandas-Sorting/

* 원소/조합 세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/

In [165]:
df = pd.read_csv("bike.csv")
df.head(2)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40

In [166]:
df["season"].unique()

array([1, 2, 3, 4])

In [167]:
df["season"].nunique()

4

In [168]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [169]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [170]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

In [171]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [172]:
df[["season", "holiday"]].drop_duplicates()

      season  holiday
0          1        0
372        1        1
1323       2        0
1658       2        1
2690       3        0
2762       3        1
4055       4        0
4271       4        1

In [173]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [174]:
df_ck = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_ck)

2615

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [182]:
df.groupby("cut")["price"].max()

cut
Fair         18574
Good         18788
Ideal        18806
Premium      18823
Very Good    18818
Name: price, dtype: int64

In [189]:
df_g1 = df.groupby("cut")["price"].max().reset_index()
df_g1

         cut  price
0       Fair  18574
1       Good  18788
2      Ideal  18806
3    Premium  18823
4  Very Good  18818

In [ ]:
df_ck = df.groupby("cut")[["price", "carat"]].max()
# df_ck = df.groupby("cut")[["price", "carat"]].max().reset_index()
df_ck

In [185]:
df_ck.columns

Index(['price', 'carat'], dtype='str')

In [ ]:
df_g2 = df.groupby("cut")[["price", "carat"]].agg({"price": "max", "carat": "min"}).reset_index()
df_g2 # 🎯🎯기출 전처리 유형⭐⭐

In [192]:
df_g3 = df.groupby(["cut", "color"])["carat"].mean().reset_index()
df_g3.tail()

          cut color     carat
30  Very Good     F  0.740961
31  Very Good     G  0.766799
32  Very Good     H  0.915948
33  Very Good     I  1.046952
34  Very Good     J  1.133215

* 문자열 처리: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [196]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [201]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [ ]:
df_tx["v2"].replace("aaa", "🔥")

In [ ]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

In [200]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [202]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [203]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [204]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [206]:
df_tx["v2"].str.replace("a", "")

0     bc
1
2    ccc
Name: v2, dtype: str

In [214]:
df_tx["v3"][0]

123

In [211]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [215]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"]

0              123
1        1234-5678
2    010-1234-5678
Name: v4, dtype: str

In [216]:
df_tx["v4"][0]

'123'

In [217]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [218]:
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: str

In [219]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4

      0     1     2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [220]:
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_2

   v4_0  v4_1  v4_2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [ ]:
df_tx_v4_3 = df_tx_v4_2.fillna("🥗")
df_tx_v4_3

* 시간 데이터: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [227]:
ser_t1 = pd.Series(["2026-10-28", "2026-10-29", "2026-10-30"])
ser_t2 = pd.Series(["2026년 10월 28일", "2026년 10월 29일", "2026년 10월 30일"])
ser_t3 = pd.Series([20261028, 20261029, 20261030])
ser_t4 = pd.Series([1234, 2345, 3456])

In [228]:
pd.to_datetime(ser_t1)

0   2026-10-28
1   2026-10-29
2   2026-10-30
dtype: datetime64[us]

In [230]:
# pd.to_datetime(ser_t2)

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [231]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-10-28
1   2026-10-29
2   2026-10-30
dtype: datetime64[us]

In [232]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020261028
1   1970-01-01 00:00:00.020261029
2   1970-01-01 00:00:00.020261030
dtype: datetime64[ns]

In [233]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-10-28
1   2026-10-29
2   2026-10-30
dtype: datetime64[us]

In [234]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [235]:
pd.to_datetime(ser_t4, origin = "2026-10-28", unit = "D")

0   2030-03-15
1   2033-03-30
2   2036-04-14
dtype: datetime64[s]

In [239]:
df_bike = pd.read_csv("bike.csv")
df_dt2 = df_bike[["datetime"]].copy() # 깊은 복사!!
# 특히 시험버전의 Pandas는 각종 함수/메서드에서 깊은 복사를 지원하지 않아
# 데이터 핸들링 시 예상치 못한 문제가 발생할 수 있음.
# 불안하면 .copy() 사용 권장.

In [242]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출🎯🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0) # 주말 1, 주중 0
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [243]:
df_dt2.head(2)

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,1,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,1,2011-01-01 10:00:00

In [247]:
df_dt = pd.DataFrame(dict(date = ["2077-08-01", "2077-08-02", "2077-08-03"]))
df_dt["origin"] = "2077-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2077-08-01 2077-01-01 212 days     212
1 2077-08-02 2077-01-01 213 days     213
2 2077-08-03 2077-01-01 214 days     214

카이제곱검정에서 산출하는 기대도수를 직접 지시사항을 따라 산출하는 문제.

In [256]:
df_t = pd.DataFrame(dict(date = pd.date_range("2024-01-01", "2024-01-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(), (df_t["v_s1"] + df_t["v_sn1"]) / 2, df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate()
df_t

        date      v   v_s1  v_sn1  v_fill_1  v_fill_2
0 2024-01-01  100.0    NaN  200.0     100.0     100.0
1 2024-01-02  200.0  100.0  300.0     200.0     200.0
2 2024-01-03  300.0  200.0    NaN     300.0     300.0
3 2024-01-04    NaN  300.0  500.0     400.0     400.0
4 2024-01-05  500.0    NaN  600.0     500.0     500.0
5 2024-01-06  600.0  500.0  700.0     600.0     600.0
6 2024-01-07  700.0  600.0    NaN     700.0     700.0

* .melt(): https://datadoctorblog.com/2023/05/07/Py-Basic-Pandas-Melt/

In [261]:
df_e = pd.read_csv("elec_load_2017_7d.csv")
df_e.head(2)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330
1,2017,1,2,57067,55148,53983,53571,54027,55388,57753,...,72228,71945,72641,73387,72294,69989,67893,66504,67435,69275

In [262]:
df_e.shape

(7, 27)

In [ ]:
df_m1 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head(3)

In [ ]:
df_m2 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"], 
                  var_name = "HOUR", value_name = "LOAD")
df_m2.head(3)

In [265]:
# regex: regular expression, 정규표현식
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지

In [ ]:
df_m2.tail()

In [268]:
df_m2["HOUR"].str.replace("[0-9]", "", regex = True).head()

0    XHR
1    XHR
2    XHR
3    XHR
4    XHR
Name: HOUR, dtype: str

* pivoting: https://datadoctorblog.com/2023/05/10/Py-Basic-Pandas-Pivoting/

In [ ]:
df_dia = pd.read_csv("diamonds.csv")
df_dia.head(2)

In [274]:
pd.crosstab(index = df_dia["cut"], columns = df_dia["color"],
            values = df_dia["price"], aggfunc = "min")

color        D    E    F    G    H    I    J
cut
Fair       536  337  496  369  659  735  416
Good       361  327  357  394  368  351  335
Ideal      367  326  408  361  357  348  340
Premium    367  326  342  382  368  334  363
Very Good  357  352  357  354  337  336  336

In [275]:
df_ck = df_dia.groupby(["cut", "color"])["price"].min().reset_index()
df_ck.head()

    cut color  price
0  Fair     D    536
1  Fair     E    337
2  Fair     F    496
3  Fair     G    369
4  Fair     H    659

In [276]:
df_dia.pivot_table(index = "cut", columns = "color", 
                   values = "price", aggfunc = "min")

color        D    E    F    G    H    I    J
cut
Fair       536  337  496  369  659  735  416
Good       361  327  357  394  368  351  335
Ideal      367  326  408  361  357  348  340
Premium    367  326  342  382  368  334  363
Very Good  357  352  357  354  337  336  336

* merge: https://datadoctorblog.com/2023/05/22/Py-Basic-Pandas-Merge/

In [ ]:
df_bike.head(2)

In [282]:
df_b1 = df_bike.iloc[:4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8 ]
df_b1

   weather  temp   atemp
0        1  9.84  14.395
1        1  9.02  13.635
2        1  9.02  13.635
3        1  9.84  14.395

In [283]:
df_b2

   temp   atemp  humidity
1  9.02  13.635        80
2  9.02  13.635        80
3  9.84  14.395        75
4  9.84  14.395        75

In [ ]:
pd.concat([df_b1, df_b2])

In [294]:
df_bind1 = pd.concat([df_b1, df_b2])
df_bind1.isna().sum()

weather     4
temp        0
atemp       0
humidity    4
dtype: int64

In [ ]:
pd.concat([df_b1, df_b2], axis = 1)

In [292]:
pd.concat([df_b1, df_b2.reset_index(drop = True)], axis = 1)

   weather  temp   atemp  temp   atemp  humidity
0        1  9.84  14.395  9.02  13.635        80
1        1  9.02  13.635  9.02  13.635        80
2        1  9.02  13.635  9.84  14.395        75
3        1  9.84  14.395  9.84  14.395        75

In [293]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)

   weather  temp   atemp  temp_y  atemp_y  humidity_y
0        1  9.84  14.395    9.02   13.635          80
1        1  9.02  13.635    9.02   13.635          80
2        1  9.02  13.635    9.84   14.395          75
3        1  9.84  14.395    9.84   14.395          75

In [ ]:
df_bike.head(2)

In [ ]:
df_bike2 = df_bike.iloc[:, [0, 5, 6, 7]]
df_bike2.head(2)

In [308]:
df_s1 = df_bike2.sample(n = 300, random_state = 100).sort_values("datetime").reset_index(drop = True)
df_s2 = df_bike2.sample(n = 300, random_state = 200).sort_values("datetime").reset_index(drop = True)
len(df_s1), len(df_s2)

(300, 300)

In [309]:
df_s1["datetime"] = pd.to_datetime(df_s1["datetime"])
df_s1["date"] = df_s1["datetime"].dt.date
df_s2["datetime"] = pd.to_datetime(df_s2["datetime"])
df_s2["date"] = df_s2["datetime"].dt.date

In [ ]:
df_s1.head()

In [ ]:
df_s2.head()

In [ ]:
df_s1["date"].nunique(), df_s2["date"].nunique()

In [315]:
df_s1_g = df_s1.groupby("date")["humidity"].max().reset_index()
df_s1_g = df_s1_g.rename(columns = {"humidity": "s1_h"})
df_s2_g = df_s2.groupby("date")["humidity"].max().reset_index()
df_s2_g = df_s2_g.rename(columns = {"humidity": "s2_h"})

In [ ]:
df_join1 = pd.merge(df_s1_g, df_s2_g, on = "date", how = "inner")
df_join1.head()

In [319]:
len(df_join1)

106

In [320]:
df_join2 = pd.merge(df_s1_g, df_s2_g, on = "date", how = "left")
df_join2.head()

         date  s1_h   s2_h
0  2011-01-02    77  100.0
1  2011-01-03    50   69.0
2  2011-01-04    56    NaN
3  2011-01-05    47    NaN
4  2011-01-09    40    NaN

In [325]:
# df_bike.max()
df_bike.apply("max", axis = 0)

datetime      2012-12-19 23:00:00
season                          4
holiday                         1
workingday                      1
weather                         4
temp                         41.0
atemp                      45.455
humidity                      100
windspeed                 56.9969
casual                        367
registered                    886
count                         977
dtype: object

In [321]:
df_bike.head(2)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40