### 교육 중에 작성하는 모든 코드는 github 저장소를 통해 공유드립니다.

In [72]:
import numpy as np
import pandas as pd

In [73]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [74]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [75]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [76]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [77]:
df_s.shape

(3, 3)

In [78]:
df_s["shape"] # series

0    A
1    B
2    C
Name: shape, dtype: str

In [79]:
df_s[["shape"]] # dataframe

  shape
0     A
1     B
2     C

In [80]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [81]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [82]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [83]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [84]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [85]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [86]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [87]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ] # AND

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [88]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ] # OR

    v1   v2 shape
1  200  500     B
2  300  600     C

In [89]:
df_ck = df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

In [90]:
df_ck

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [91]:
df_ck["v1"].sum()

np.int64(0)

In [92]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [93]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [94]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ] # f(x, y) / df.loc[ row , column ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [95]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [96]:
# 시험 기출 유형
# 변수 x부터 y까지 정규화를 실시하고 정규화된 변수명 뒤에 접미사 "_nor" 를 붙이시오.
df_s.add_suffix("_nor") # .add_prefix()

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [97]:
df_s1 = df_s
df_s1.columns = df_s1.columns + "_nor"
df_s1

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [98]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
1,KTOP 30,11520.28,-86.30,-0.74,11609.44,11702.14,11490.84,50048566,5645660149606,1208343758559140,20210503

In [99]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
29,KRX 300,1916.40,15.35,0.81,1903.57,1916.40,1892.36,244040965,11708937073166,2043945386926060,20210504

In [100]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [101]:
df["종가"].idxmax()

117

In [102]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [103]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [104]:
df.loc[117, ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [105]:
df.loc[[117], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [106]:
df_s[["v1_nor"]]

   v1_nor
0     100
1     200
2     300

In [107]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [108]:
# df_sub.info()

In [109]:
df_sub.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species             str
dtype: object

In [110]:
df_sub.isna().sum() # 🌟🌟🌟

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [111]:
True + False

1

In [112]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [113]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [114]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [115]:
df_sub.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='str')

In [116]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [117]:
df_sub2 = df.head().reset_index(drop = True) # 필터링, 정렬 등 특정 조작 이후 인덱스 초기화 까지 필요한 경우
df_sub2 = df.head().copy() # 깊은 복사가 필요한 경우(불필요한 경고 방지 및 객체간 연동 해제)

In [118]:
df_sub2["Petal.Length"] = df_sub2["Petal.Length"].fillna(df_sub2["Petal.Length"].mean())
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [119]:
# df_sub2.set_index("Species") # .reset_index()
df_sub2.set_index("Species").reset_index() # 머신러닝 모델링 시 종속변수를 가장 앞으로 편리하게 옮기는 방법.
# 기존 변수의 위치에 관계 없이 가장 앞으로 옮길 수 있음. (단, 기존 index 정보를 보존할 필요가 없는 경우)

  Species  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0  setosa           5.1          NaN           1.4          0.2
1  setosa           4.9          3.0           1.4          0.2
2  setosa           4.7          3.2           1.3          0.2
3  setosa           4.6          3.1           1.5          0.2
4  setosa           5.0          3.6           1.4          0.2

In [120]:
df_sub2["Sepal.Length"].astype("str") + "cm"

0    5.1cm
1    4.9cm
2    4.7cm
3    4.6cm
4    5.0cm
Name: Sepal.Length, dtype: str

* 정렬: https://datadoctorblog.com/2023/04/25/Py-Basic-Pandas-Sorting/

In [121]:
df = pd.read_csv("diamonds.csv")
df["color"].value_counts().sort_index()

color
D     6775
E     9797
F     9542
G    11292
H     8304
I     5422
J     2808
Name: count, dtype: int64

* 원소/조합 세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/
* crosstab(): https://datadoctorblog.com/2023/05/06/Py-Basic-Pandas-Crosstab/

In [122]:
df = pd.read_csv("bike.csv")
df.head(2)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40

In [123]:
df["season"].unique()

array([1, 2, 3, 4])

In [124]:
df["season"].nunique() # number, number of

4

In [125]:
df["season"].drop_duplicates() # 기존의 객체 유형을 보존. dataframe에 사용하면 중복 행 제거.

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [126]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

In [127]:
df["season"].value_counts(normalize = True) # 비율 계산

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [128]:
df[["season", "holiday"]].drop_duplicates()

      season  holiday
0          1        0
372        1        1
1323       2        0
1658       2        1
2690       3        0
2762       3        1
4055       4        0
4271       4        1

In [129]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [130]:
df_ck = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_ck)

2615

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [131]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [132]:
# df["price"]
# df[["price", "carat"]]

In [133]:
df.groupby("color")["price"].max()

color
D    18693
E    18731
F    18791
G    18818
H    18803
I    18823
J    18710
Name: price, dtype: int64

In [134]:
df.groupby("color")[["price", "carat"]].max()

       price  carat
color
D      18693   3.40
E      18731   3.05
F      18791   3.01
G      18818   3.01
H      18803   4.13
I      18823   4.01
J      18710   5.01

In [135]:
df.groupby(["color", "clarity"])["price"].max()

color  clarity
D      I1         15964
       IF         18542
       SI1        18468
       SI2        18693
       VS1        17936
       VS2        18318
       VVS1       17932
       VVS2       17545
E      I1         11548
       IF         18700
       SI1        18731
       SI2        18477
       VS1        18729
       VS2        18557
       VVS1       16256
       VVS2       18188
F      I1         10685
       IF         18552
       SI1        18759
       SI2        18784
       VS1        18780
       VS2        18791
       VVS1       18777
       VVS2       18614
G      I1         13203
       IF         18806
       SI1        18818
       SI2        18804
       VS1        18419
       VS2        18700
       VVS1       18445
       VVS2       18768
H      I1         17329
       IF         16300
       SI1        18803
       SI2        18745
       VS1        18522
       VS2        18659
       VVS1       14603
       VVS2       17267
I      I1         16193
       IF         12725
       SI1        18797
       SI2        18756
       VS1        18795
       VS2        18823
       VVS1       15654
       VVS2       15952
J      I1         18531
       IF         18594
       SI1        18508
       SI2        18710
       VS1        18706
       VS2        18701
       VVS1       17891
       VVS2       17214
Name: price, dtype: int64

In [136]:
df_g1 = df.groupby("color")["price"].max().reset_index()
df_g1

  color  price
0     D  18693
1     E  18731
2     F  18791
3     G  18818
4     H  18803
5     I  18823
6     J  18710

In [137]:
df_g2 = df.groupby("cut")["price"].agg(["max", "min"]).reset_index()
df_g2

         cut    max  min
0       Fair  18574  337
1       Good  18788  327
2      Ideal  18806  326
3    Premium  18823  326
4  Very Good  18818  336

In [138]:
df_g3 = df.groupby("cut")[["price", "carat"]].agg({"price": "mean", 
                                                   "carat": "max"}).reset_index()
df_g3 # 시험 기출 전처리 유형 🎯

         cut        price  carat
0       Fair  4358.757764   5.01
1       Good  3928.864452   3.01
2      Ideal  3457.541970   3.50
3    Premium  4584.257704   4.01
4  Very Good  3981.759891   4.00

In [139]:
df_g4 = df.groupby("color")["price"].agg(lambda x: x.mean() + 10000).reset_index()
df_g4

  color         price
0     D  13169.954096
1     E  13076.752475
2     F  13724.886397
3     G  13999.135671
4     H  14486.669196
5     I  15091.874954
6     J  15323.818020

In [140]:
df_s["a"] = 1

In [141]:
df_s["b"] = df_s["v1_nor"] + df_s["v2_nor"]
df_s

   v1_nor  v2_nor shape_nor  a    b
0     100     400         A  1  500
1     200     500         B  1  700
2     300     600         C  1  900

In [142]:
df_s["a"] = 999
df_s

   v1_nor  v2_nor shape_nor    a    b
0     100     400         A  999  500
1     200     500         B  999  700
2     300     600         C  999  900

In [143]:
# "color" 변수에 9000개 이상 존재하는 원소를 확인하고 해당 원소가 존재하는 행을 뽑아
# "df2" 객체에 저장하시오.

In [144]:
ser_cnt = df["color"].value_counts()
ser_cnt = ser_cnt[ser_cnt >= 9000]
ser_cnt.index

Index(['G', 'E', 'F'], dtype='str', name='color')

In [145]:
df2 = df.loc[df["color"].isin(ser_cnt.index), ]
df2["color"].unique()

<StringArray>
['E', 'F', 'G']
Length: 3, dtype: str

* 문자 데이터: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [146]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"], 
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [147]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [148]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [149]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

0    abc
1      🔥
2      🩵
Name: v2, dtype: str

In [150]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [151]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [152]:
df_tx["v4"] = df_tx["v2"].str.replace("a", "🔥")
df_tx

    v1   v2             v3   v4
0  100  abc            123  🔥bc
1  200  aaa      1234-5678  🔥🔥🔥
2  300  ccc  010-1234-5678  ccc

In [153]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [154]:
~df_tx["v2"].str.contains("a") # ^[^a]*?$

0    False
1    False
2     True
Name: v2, dtype: bool

In [155]:
df_tx2 = df_tx.loc[df_tx["v2"].str.contains("a"), ]
df_tx2

    v1   v2         v3   v4
0  100  abc        123  🔥bc
1  200  aaa  1234-5678  🔥🔥🔥

In [156]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [157]:
df_tx["v5"] = df_tx["v3"].astype("str")
df_tx["v5"][0]

'123'

In [158]:
df_tx

    v1   v2             v3   v4             v5
0  100  abc            123  🔥bc            123
1  200  aaa      1234-5678  🔥🔥🔥      1234-5678
2  300  ccc  010-1234-5678  ccc  010-1234-5678

In [159]:
df_tx.dtypes # object 형식은 문자가 1개 이상 포함된 것을 뜻함.

v1     int64
v2       str
v3    object
v4       str
v5       str
dtype: object

In [160]:
df_tx["v5"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v5, dtype: object

In [161]:
df_tx["v5"].str.split("-").explode().reset_index()

   index    v5
0      0   123
1      1  1234
2      1  5678
3      2   010
4      2  1234
5      2  5678

In [162]:
df_tx_v5 = df_tx["v5"].str.split("-", expand = True)
df_tx_v5_2 = df_tx_v5.add_prefix("v5_")
df_tx_v5_2

   v5_0  v5_1  v5_2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [163]:
df_tx_v5_3 = df_tx_v5_2.fillna("🥗")
df_tx_v5_3

   v5_0  v5_1  v5_2
0   123     🥗     🥗
1  1234  5678     🥗
2   010  1234  5678

In [164]:
df_tx["v2"]

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [165]:
df_tx["v2"].str.replace("a", "")

0     bc
1
2    ccc
Name: v2, dtype: str

* 시간 데이터: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [166]:
ser_t1 = pd.Series(["2077-12-18", "2077-12-19", "2077-12-20"])
ser_t2 = pd.Series(["2077년 12월 18일", "2077년 12월 19일", "2077년 12월 20일"])
ser_t3 = pd.Series([20241218, 20241219, 20241220])
ser_t4 = pd.Series([1234, 2345, 3456])

In [167]:
pd.to_datetime(ser_t1)

0   2077-12-18
1   2077-12-19
2   2077-12-20
dtype: datetime64[us]

In [168]:
# pd.to_datetime(ser_t2) # 에러 발생!!

In [169]:
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2077-12-18
1   2077-12-19
2   2077-12-20
dtype: datetime64[us]

In [170]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020241218
1   1970-01-01 00:00:00.020241219
2   1970-01-01 00:00:00.020241220
dtype: datetime64[ns]

In [171]:
pd.to_datetime(ser_t3.astype("str"))
# pd.to_datetime(ser_t3.astype("str"), format = "%Y%m%d")

0   2024-12-18
1   2024-12-19
2   2024-12-20
dtype: datetime64[us]

In [172]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [173]:
pd.to_datetime(ser_t4, origin = "2026-03-11", unit = "D")

0   2029-07-27
1   2032-08-11
2   2035-08-27
dtype: datetime64[s]

In [174]:
df = pd.read_csv("bike.csv")
df_dt2 = df[["datetime"]].copy()
df_dt2.head(2)

              datetime
0  2011-01-01 00:00:00
1  2011-01-01 01:00:00

In [175]:
df_dt2.dtypes

datetime    str
dtype: object

In [176]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0) # 주말 1, 주중 0
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [177]:
df_dt2.head(2)

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,1,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,1,2011-01-01 10:00:00

In [178]:
df_dt2.dtypes

datetime    datetime64[us]
date                object
yyyymm                 str
year                 int32
month                int32
wday                 int32
wend                 int64
hour                 int32
dt_s9h      datetime64[us]
dtype: object

In [179]:
# 날짜 비교 가능.
# 점심 이후 설명드립니다.

In [180]:
pd.__version__

'3.0.1'

In [181]:
df_dt = pd.DataFrame(dict(date = ["2077-08-01", "2077-08-02", "2077-08-03"]))
df_dt["origin"] = "2077-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2077-08-01 2077-01-01 212 days     212
1 2077-08-02 2077-01-01 213 days     213
2 2077-08-03 2077-01-01 214 days     214

In [182]:
df_dt.dtypes

date       datetime64[us]
origin     datetime64[us]
diff      timedelta64[us]
diff_d              int64
dtype: object

In [183]:
df_t = pd.DataFrame(dict(date = pd.date_range("2024-01-01", "2024-01-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_s2"] = df_t["v"].shift(2)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(),
                            (df_t["v_s1"] + df_t["v_sn1"]) / 2,
                            df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate()

In [184]:
df_t

        date      v   v_s1   v_s2  v_sn1  v_fill_1  v_fill_2
0 2024-01-01  100.0    NaN    NaN  200.0     100.0     100.0
1 2024-01-02  200.0  100.0    NaN  300.0     200.0     200.0
2 2024-01-03  300.0  200.0  100.0    NaN     300.0     300.0
3 2024-01-04    NaN  300.0  200.0  500.0     400.0     400.0
4 2024-01-05  500.0    NaN  300.0  600.0     500.0     500.0
5 2024-01-06  600.0  500.0    NaN  700.0     600.0     600.0
6 2024-01-07  700.0  600.0  500.0    NaN     700.0     700.0

* .melt(): https://datadoctorblog.com/2023/05/07/Py-Basic-Pandas-Melt/
* .pivot()/.pivot_table(): https://datadoctorblog.com/2023/05/10/Py-Basic-Pandas-Pivoting/

In [185]:
df_e = pd.read_csv("elec_load_2017_7d.csv")
df_e.head(2)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330
1,2017,1,2,57067,55148,53983,53571,54027,55388,57753,...,72228,71945,72641,73387,72294,69989,67893,66504,67435,69275

In [186]:
df_e_m1 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"],
                    var_name = "HOUR", value_name = "LOAD") 
df_e_m1.head()

   YEAR  MONTH  DAY  HOUR   LOAD
0  2017      1    1  X1HR  60178
1  2017      1    2  X1HR  57067
2  2017      1    3  X1HR  66263
3  2017      1    4  X1HR  68403
4  2017      1    5  X1HR  68053

In [187]:
df_e_m1["h1"] = df_e_m1["HOUR"].str.replace("X", "").str.replace("HR", "")
df_e_m1["h2"] = df_e_m1["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_e_m1["h3"] = df_e_m1["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_e_m1["h4"] = df_e_m1["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지
# regex: regular expression(정규표현식)
df_e_m1.tail()

     YEAR  MONTH  DAY   HOUR   LOAD  h1  h2  h3  h4
163  2017      1    3  X24HR  71346  24  24  24  24
164  2017      1    4  X24HR  70834  24  24  24  24
165  2017      1    5  X24HR  66687  24  24  24  24
166  2017      1    6  X24HR  63214  24  24  24  24
167  2017      1    7  X24HR  69219  24  24  24  24

In [188]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [189]:
x = df.loc[(df["cut"] == "Fair") & (df["color"] == "D"), "price"]
round(x.mean())

4291

In [190]:
df_ck1 = pd.crosstab(index = df["cut"], columns = df["color"], values = df["price"],
                     aggfunc = lambda x: round(x.mean()))
df_ck1

color         D     E     F     G     H     I     J
cut
Fair       4291  3682  3827  4239  5136  4685  4976
Good       3405  3424  3496  4123  4276  5079  4574
Ideal      2629  2598  3375  3721  3889  4452  4918
Premium    3631  3539  4325  4501  5217  5946  6295
Very Good  3470  3215  3779  3873  4535  5256  5104

In [191]:
def udf_mean_r(x):
    return round(x.mean())
    
df_ck2 = df.groupby(["cut", "color"])["price"].agg(udf_mean_r).reset_index()
df_ck2.head()

    cut color  price
0  Fair     D   4291
1  Fair     E   3682
2  Fair     F   3827
3  Fair     G   4239
4  Fair     H   5136

In [192]:
df_ck3 = df.pivot_table(index = "cut", columns = "color", values = "price", 
                        aggfunc = udf_mean_r)
df_ck3

color         D     E     F     G     H     I     J
cut
Fair       4291  3682  3827  4239  5136  4685  4976
Good       3405  3424  3496  4123  4276  5079  4574
Ideal      2629  2598  3375  3721  3889  4452  4918
Premium    3631  3539  4325  4501  5217  5946  6295
Very Good  3470  3215  3779  3873  4535  5256  5104

* 데이터 병합: https://datadoctorblog.com/2023/05/22/Py-Basic-Pandas-Merge/

In [193]:
df_bike = pd.read_csv("bike.csv")
df_bike.head(1)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16

In [194]:
df_b1 = df_bike.iloc[ :4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8]

In [195]:
df_b1

   weather  temp   atemp
0        1  9.84  14.395
1        1  9.02  13.635
2        1  9.02  13.635
3        1  9.84  14.395

In [196]:
df_b2

   temp   atemp  humidity
1  9.02  13.635        80
2  9.02  13.635        80
3  9.84  14.395        75
4  9.84  14.395        75

In [ ]:
pd.concat([df_b1, df_b2])
# pd.concat(df_b1, df_b2) # 에러!!

In [ ]:
pd.concat([df_b1, df_b2], axis = 1)

In [ ]:
# pd.concat([df_b1, df_b2.reset_index(drop = True)], axis = 1)
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)

In [205]:
df_cat = pd.concat([df_b1, df_b2], axis = 1)
df_cat.iloc[1:4, ]

   weather  temp   atemp  temp   atemp  humidity
1      1.0  9.02  13.635  9.02  13.635      80.0
2      1.0  9.02  13.635  9.02  13.635      80.0
3      1.0  9.84  14.395  9.84  14.395      75.0

In [ ]:
df_cat.isna().sum()

In [207]:
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [209]:
df_g1 = df.loc[df["color"] != "E", ].groupby("color")["table"].max().reset_index()
df_g2 = df.loc[df["color"] != "G", ].groupby("color")["price"].max().reset_index()

In [213]:
# df_g_join = pd.merge(df_g1, df_g2, on = "color", how = "inner")
df_g_join = pd.merge(df_g1,             df_g2, 
                     left_on = "color", right_on = "color", 
                     how = "inner")
df_g_join

  color  table  price
0     D   73.0  18693
1     F   95.0  18791
2     H   73.0  18803
3     I   70.0  18823
4     J   68.0  18710

In [214]:
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [215]:
df_sub1 = df.loc[df["clarity"].str.contains("^S"), ] # 대문자 "S" 로 시작하는
df_sub1["clarity"].unique()

<StringArray>
['SI2', 'SI1']
Length: 2, dtype: str

In [217]:
df_sub2 = df.loc[df["clarity"].str.contains("2$"), ] # 2로 끝나는
df_sub2["clarity"].unique()

<StringArray>
['SI2', 'VS2', 'VVS2']
Length: 3, dtype: str