## 교육 중 작성하는 코드는 깃허브 통해서 공유 드립니다.

In [2]:
import pandas as pd

In [ ]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

In [ ]:
df_s.iloc[:2, ]

In [ ]:
df_s.loc[:2, ]

In [ ]:
df_s.v1

In [ ]:
df_s.shape

In [ ]:
df_s["shape"]

In [ ]:
df_s.iloc[:, :-1]

In [ ]:
df_s.loc[:, "v2":]

In [15]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [16]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [17]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [18]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [19]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [23]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [26]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [27]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [28]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [29]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [30]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [ ]:
df_s1 = df_s.add_prefix("pre_")
df_s1

In [32]:
df_s2 = df_s.add_suffix("_nor") # 기출유형
df_s2

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [ ]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

In [ ]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

In [43]:
df["종가"].idxmax()

117

In [44]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [45]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [47]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()

In [ ]:
df_sub.info()

In [49]:
pd.__version__

'3.0.1'

In [ ]:
df_sub.columns

In [ ]:
df_sub.count()

In [ ]:
df_sub.dtypes

In [ ]:
df_sub.isna().sum() # ⭐⭐⭐ 중요!

In [ ]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

In [ ]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

In [60]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa