In [1]:
import numpy as np
import pandas as pd

In [2]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [3]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [4]:
df_s.loc[:2, ] # 슬라이싱(연속 범위 지정)에서 지정한 것 까지 선택됨.

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [5]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [6]:
df_s.shape # row, column

(3, 3)

In [7]:
df_s["shape"] # Series

0    A
1    B
2    C
Name: shape, dtype: str

In [8]:
df_s[["shape"]] # DataFrame

  shape
0     A
1     B
2     C

In [9]:
df_s.loc[:, "shape"] # 굳이?

0    A
1    B
2    C
Name: shape, dtype: str

In [10]:
df_s.loc[:, ["shape"]] # 굳이?

  shape
0     A
1     B
2     C

In [11]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [12]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [13]:
df_s.loc[:, df_s.columns.str.contains("v")] # "v"가 포함된 변수만 선택

    v1   v2
0  100  400
1  200  500
2  300  600

In [14]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [15]:
df_s.loc[df_s["v1"] != 200, ] # not equal

    v1   v2 shape
0  100  400     A
2  300  600     C

In [16]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [17]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [18]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [19]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [20]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [21]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [22]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [23]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [24]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [25]:
df_s1 = df_s.add_prefix("prefix_")
df_s1

   prefix_v1  prefix_v2 prefix_shape
0        100        400            A
1        200        500            B
2        300        600            C

In [26]:
df_s2 = df_s.add_suffix("_nor")
df_s2

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [27]:
import os
os.getcwd() # 현재 작업폴더

'C:\\Users\\PC\\Desktop\\python_class'

In [28]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
1,KTOP 30,11520.28,-86.30,-0.74,11609.44,11702.14,11490.84,50048566,5645660149606,1208343758559140,20210503

In [29]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
29,KRX 300,1916.40,15.35,0.81,1903.57,1916.40,1892.36,244040965,11708937073166,2043945386926060,20210504
58,KRX 300,1927.40,11.00,0.57,1916.50,1927.40,1904.76,341534594,13004811637843,2059578026871265,20210506
87,KRX 300,1936.40,9.00,0.47,1926.59,1942.80,1925.24,253210064,11101387594368,2070880919861705,20210507
116,KRX 300,1968.47,32.07,1.66,1938.63,1973.17,1938.63,294421965,13784089230905,2105851479694870,20210510
145,KRX 300,1936.37,-32.10,-1.63,1962.35,1962.35,1929.74,339313903,15976844135869,2075382637364310,20210511
174,KRX 300,1903.99,-32.38,-1.67,1936.18,1936.82,1891.55,352799341,17136393156387,2043316163563660,20210512
203,KRX 300,1878.46,-25.53,-1.34,1893.72,1899.65,1869.37,402046342,16819555547844,2014899605250130,20210513
232,KRX 300,1899.13,20.67,1.10,1884.85,1905.26,1884.85,229722051,11413338490975,2038805937109210,20210514
261,KRX 300,1891.72,-7.41,-0.39,1906.35,1912.03,1882.03,258826078,11333749894174,2027913472817160,20210517
290,KRX 300,1913.67,21.95,1.16,1892.13,1917.43,1892.13,248484463,11503457331908,2053066878361790,20210518
319,KRX 300,1906.26,-7.41,-0.39,1914.61,1914.61,1894.97,224240546,10906767355146,2047273506168110,20210520
348,KRX 300,1907.38,1.12,0.06,1912.44,1932.91,1902.03,247944350,12200080796814,2042477090377600,20210521
377,KRX 300,1897.69,-9.69,-0.51,1906.60,1910.68,1893.57,210439901,9568918143070,2035955475360540,20210524
406,KRX 300,1915.26,17.57,0.93,1903.17,1916.85,1900.82,208362193,9591985036024,2054548999380540,20210525
435,KRX 300,1911.68,-3.58,-0.19,1915.76,1922.77,1907.37,257307289,10837464472787,2051152192863740,20210526
464,KRX 300,1910.09,-1.59,-0.08,1913.55,1915.55,1894.84,327607567,17156385452981,2043966667110420,20210527
493,KRX 300,1922.87,12.78,0.67,1913.77,1929.84,1912.48,234219802,10813228145679,2058019926179550,20210528
522,KRX 300,1932.64,9.77,0.51,1924.63,1933.75,1916.75,278319769,11293303810625,2068979877957040,20210531

In [30]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [31]:
df["종가"].idxmax()

117

In [32]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [33]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [34]:
df = pd.read_csv("iris_missing.csv")

In [35]:
df_sub = df.head()

In [36]:
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [37]:
df_sub.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  5 non-null      float64
 1   Sepal.Width   4 non-null      float64
 2   Petal.Length  4 non-null      float64
 3   Petal.Width   5 non-null      float64
 4   Species       5 non-null      str
dtypes: float64(4), str(1)
memory usage: 332.0 bytes

In [38]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [39]:
df_sub.dtypes # Species의 경우 Pandas 3버전 이전 버전의 경우 object 로 표기됨.

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species             str
dtype: object

In [40]:
df_sub.isna()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0         False         True          True        False    False
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False

In [41]:
df_sub.isna().sum()

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [42]:
ser_na = pd.Series([100, np.nan, 200, np.nan, np.nan])
ser_na

0    100.0
1      NaN
2    200.0
3      NaN
4      NaN
dtype: float64

In [43]:
ser_na.fillna(0)

0    100.0
1      0.0
2    200.0
3      0.0
4      0.0
dtype: float64

In [44]:
ser_na2 = ser_na.fillna(ser_na.mean())
ser_na2

0    100.0
1    150.0
2    200.0
3    150.0
4    150.0
dtype: float64

In [45]:
# 최신버전
ser_na.ffill() # 결측이 있을 경우 앞에(forward)있는 관측값을 끌어와서 메꿈

0    100.0
1    100.0
2    200.0
3    200.0
4    200.0
dtype: float64

In [46]:
ser_na.bfill() # 결측이 있을 경우 뒤에(backward)있는 관측값을 끌어와서 메꿈

0    100.0
1    200.0
2    200.0
3      NaN
4      NaN
dtype: float64

In [47]:
# 시험버전
# ser_na.fillna(method = "ffill")
# ser_na.fillna(method = "bfill")

In [48]:
# 특정 수치형 변수를 IQR 기준으로 이상치를 판별하고,
# 해당 이상치들을 결측치로 치환한 다음.
# 각 결측치와 가장 가까운 앞쪽의 관측치를 사용하여 결측치를 대치

In [49]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [50]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [51]:
df_sub3 = df_sub.dropna()
len(df_sub3)

4

In [52]:
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())

In [53]:
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [54]:
df_sub4 = df_sub.set_index("Species").reset_index()
df_sub4 # 특정 변수의 기존 위치에 관계 없이 가장 앞(왼쪽)으로 옮길 수 있음.
# 모델링에서 종속변수를 가장 앞으로 옮기고자 하는 경우 유용.

  Species  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0  setosa           5.1          NaN           1.4          0.2
1  setosa           4.9          3.0           1.4          0.2
2  setosa           4.7          3.2           1.3          0.2
3  setosa           4.6          3.1           1.5          0.2
4  setosa           5.0          3.6           1.4          0.2

In [55]:
df_sub4["new_col"] = df_sub4["Sepal.Length"].astype("str") + "cm"
df_sub4

  Species  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width new_col
0  setosa           5.1          NaN           1.4          0.2   5.1cm
1  setosa           4.9          3.0           1.4          0.2   4.9cm
2  setosa           4.7          3.2           1.3          0.2   4.7cm
3  setosa           4.6          3.1           1.5          0.2   4.6cm
4  setosa           5.0          3.6           1.4          0.2   5.0cm

In [56]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [57]:
df["clarity"].value_counts().sort_index()

clarity
I1        741
IF       1790
SI1     13065
SI2      9194
VS1      8171
VS2     12258
VVS1     3655
VVS2     5066
Name: count, dtype: int64

* 정렬: https://datadoctorblog.com/2023/04/25/Py-Basic-Pandas-Sorting/
* 원소/조합 세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/
* crosstab(): https://datadoctorblog.com/2023/05/06/Py-Basic-Pandas-Crosstab/

In [58]:
df = pd.read_csv("bike.csv")

In [59]:
df["season"].unique()

array([1, 2, 3, 4])

In [60]:
df["season"].nunique()

4

In [61]:
df["season"].drop_duplicates() # 실행 결과가 Pandas 객체

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [62]:
# df[["season", "holiday"]].unique() # 데이터프레임은 지원하지 않음
df[["season", "holiday"]].drop_duplicates() # 중복 행 제거

      season  holiday
0          1        0
372        1        1
1323       2        0
1658       2        1
2690       3        0
2762       3        1
4055       4        0
4271       4        1

In [63]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [64]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [65]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [66]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

In [67]:
df_sub6 = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_sub6)

2615

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [68]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [69]:
ser_g1 = df.groupby("cut")["table"].max()
ser_g1

cut
Fair         95.0
Good         66.0
Ideal        63.0
Premium      62.0
Very Good    66.0
Name: table, dtype: float64

In [70]:
df_g2 = df.groupby("cut")[["table", "price"]].max()
df_g2

           table  price
cut
Fair        95.0  18574
Good        66.0  18788
Ideal       63.0  18806
Premium     62.0  18823
Very Good   66.0  18818

In [71]:
# df_ck = df.loc[(df["cut"] == "Fair") & (df["table"] == 95), ]
# df_ck

In [72]:
df_g3 = df.groupby(["cut", "color"])["price"].min().reset_index()
df_g3.tail()

          cut color  price
30  Very Good     F    357
31  Very Good     G    354
32  Very Good     H    337
33  Very Good     I    336
34  Very Good     J    336

In [73]:
# df_g4 = df.groupby("color")[["price", "carat"]].agg(["min", "max"])
df_g4 = df.groupby("color")[["price", "carat"]].agg(["min", "max"]).reset_index()
df_g4.tail()

  color price        carat
          min    max   min   max
2     F   342  18791  0.20  3.01
3     G   354  18818  0.23  3.01
4     H   337  18803  0.23  4.13
5     I   334  18823  0.23  4.01
6     J   335  18710  0.23  5.01

In [74]:
# df_g4.columns

In [75]:
df_g5 = df.groupby("cut")["table"].max().reset_index()
df_g5

         cut  table
0       Fair   95.0
1       Good   66.0
2      Ideal   63.0
3    Premium   62.0
4  Very Good   66.0

In [76]:
df_g6 = df.groupby("color")[["price", "carat"]].agg({"price": "min", 
                                                     "carat": "max"})
df_g6 = df_g6.reset_index()
df_g6

  color  price  carat
0     D    357   3.40
1     E    326   3.05
2     F    342   3.01
3     G    354   3.01
4     H    337   4.13
5     I    334   4.01
6     J    335   5.01

In [77]:
df_g6["carat2"] = np.where(df_g6["carat"] >= 4, np.nan, df_g6["carat"])
df_g6

  color  price  carat  carat2
0     D    357   3.40    3.40
1     E    326   3.05    3.05
2     F    342   3.01    3.01
3     G    354   3.01    3.01
4     H    337   4.13     NaN
5     I    334   4.01     NaN
6     J    335   5.01     NaN

* 문자데이터: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [78]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [79]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [80]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [81]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [82]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [83]:
df_tx["v2"].str.replace("a", "")

0     bc
1
2    ccc
Name: v2, dtype: str

In [84]:
df_tx["v2_repl"] = df_tx["v2"].str.replace("a", "🛫")

In [85]:
df_tx

    v1   v2             v3 v2_repl
0  100  abc            123     🛫bc
1  200  aaa      1234-5678     🛫🛫🛫
2  300  ccc  010-1234-5678     ccc

In [86]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [87]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [88]:
df_tx.loc[df_tx["v2"].str.contains("a"), ]

    v1   v2         v3 v2_repl
0  100  abc        123     🛫bc
1  200  aaa  1234-5678     🛫🛫🛫

In [89]:
df_tx.loc[~df_tx["v2"].str.contains("a"), ]

    v1   v2             v3 v2_repl
2  300  ccc  010-1234-5678     ccc

In [90]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [91]:
df_tx["v4"] = df_tx["v3"].astype("str")

In [92]:
df_tx["v4"]

0              123
1        1234-5678
2    010-1234-5678
Name: v4, dtype: str

In [93]:
df_tx["v3"][0], df_tx["v4"][0]

(123, '123')

In [94]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [95]:
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: str

In [96]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4

      0     1     2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [97]:
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_2

   v4_0  v4_1  v4_2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [98]:
df_tx_v4_3 = df_tx_v4_2.fillna("🥗") # Pandas 3버전 이전의 경우 None으로 보일것임.
df_tx_v4_3

   v4_0  v4_1  v4_2
0   123     🥗     🥗
1  1234  5678     🥗
2   010  1234  5678

* 시간데이터: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [99]:
ser_t1 = pd.Series(["2026-03-25", "2026-03-26", "2026-03-27"])
ser_t2 = pd.Series(["2026년 03월 25일", "2026년 03월 26일", "2026년 03월 27일"])
ser_t3 = pd.Series([20260325, 20260326, 20260327])
ser_t4 = pd.Series([1234, 2345, 3456])

In [100]:
pd.to_datetime(ser_t1)

0   2026-03-25
1   2026-03-26
2   2026-03-27
dtype: datetime64[us]

In [101]:
# pd.to_datetime(ser_t2) # 에러!!!

In [102]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-03-25
1   2026-03-26
2   2026-03-27
dtype: datetime64[us]

In [103]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020260325
1   1970-01-01 00:00:00.020260326
2   1970-01-01 00:00:00.020260327
dtype: datetime64[ns]

In [104]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-03-25
1   2026-03-26
2   2026-03-27
dtype: datetime64[us]

In [105]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [106]:
pd.to_datetime(ser_t4, origin = "2026-03-25", unit = "D")

0   2029-08-10
1   2032-08-25
2   2035-09-10
dtype: datetime64[s]

In [107]:
ser_t5 = pd.Series(["2026-03-25 오전 09:12:34", "2026-03-25 오후 02:12:34"])
ser_t5

0    2026-03-25 오전 09:12:34
1    2026-03-25 오후 02:12:34
dtype: str

In [108]:
ser_t5_sub = ser_t5.str.replace("오전", "AM").str.replace("오후", "PM")
ser_t5_sub

0    2026-03-25 AM 09:12:34
1    2026-03-25 PM 02:12:34
dtype: str

In [109]:
pd.to_datetime(ser_t5_sub, format = "%Y-%m-%d %p %I:%M:%S")

0   2026-03-25 09:12:34
1   2026-03-25 14:12:34
dtype: datetime64[us]

In [ ]:
df = pd.read_csv("bike.csv")
df_dt2 = df[["datetime"]].copy()
df_dt2.head(2)

In [112]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0) # 주말 1, 주중 0
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [113]:
df_dt2.head(2)

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,1,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,1,2011-01-01 10:00:00

In [ ]:
df_dt = pd.DataFrame(dict(date = ["2026-03-25", "2026-03-26", "2026-03-27"]))
df_dt["origin"] = "2026-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

In [ ]:
# df_dt.loc[df_dt["diff"] < 85, ]
df_dt.loc[df_dt["diff_d"] < 85, ]

In [124]:
df_t = pd.DataFrame(dict(date = pd.date_range("2026-01-01", "2026-01-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))
df_t["v_s1" ] = df_t["v"].shift(1)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(), 
                            (df_t["v_s1"] + df_t["v_sn1"]) / 2, 
                            df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate()
df_t

        date      v   v_s1  v_sn1  v_fill_1  v_fill_2
0 2026-01-01  100.0    NaN  200.0     100.0     100.0
1 2026-01-02  200.0  100.0  300.0     200.0     200.0
2 2026-01-03  300.0  200.0    NaN     300.0     300.0
3 2026-01-04    NaN  300.0  500.0     400.0     400.0
4 2026-01-05  500.0    NaN  600.0     500.0     500.0
5 2026-01-06  600.0  500.0  700.0     600.0     600.0
6 2026-01-07  700.0  600.0    NaN     700.0     700.0

In [125]:
df_e = pd.read_csv("elec_load_2017_7d.csv")
df_e.head(2)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330
1,2017,1,2,57067,55148,53983,53571,54027,55388,57753,...,72228,71945,72641,73387,72294,69989,67893,66504,67435,69275

In [128]:
df_m1 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head(2)

   YEAR  MONTH  DAY variable  value
0  2017      1    1     X1HR  60178
1  2017      1    2     X1HR  57067

In [ ]:
df_m2 = df_e.melt(id_vars = ["YEAR", "MONTH", "DAY"], var_name = "HOUR", value_name = "LOAD")
df_m2.head(2)

In [130]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
# regex: regular expression(정규표현식)
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지

In [132]:
df_m2.tail(2)

     YEAR  MONTH  DAY   HOUR   LOAD  h1  h2  h3  h4
166  2017      1    6  X24HR  63214  24  24  24  24
167  2017      1    7  X24HR  69219  24  24  24  24

In [133]:
df_m2_sub = df_m2.loc[:, df_m2.columns.str.contains("^h")] # h로 시작하는.
df_m2_sub.head(2)

  h1 h2 h3 h4
0  1  1  1  1
1  1  1  1  1

In [134]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [135]:
df_g1 = df.groupby(["cut", "clarity"])["price"].agg(lambda x: round(x.mean(), 1)).reset_index()
df_g1.head(2)

    cut clarity   price
0  Fair      I1  3703.5
1  Fair      IF  1912.3

In [ ]:
df_g2 = df.pivot_table(index = "cut", columns = "clarity", values = "price", 
                       aggfunc = lambda x: round(x.mean(), 1)).reset_index()
df_g2

In [138]:
df_g3 = pd.crosstab(index = df["cut"], columns = df["clarity"], values = df["price"], 
                    aggfunc = lambda x: round(x.mean(), 1)).reset_index()
df_g3

clarity,cut,I1,IF,SI1,SI2,VS1,VS2,VVS1,VVS2
0,Fair,3703.5,1912.3,4208.3,5173.9,4165.1,4174.7,3871.4,3349.8
1,Good,3596.6,4098.3,3689.5,4580.3,3801.4,4262.2,2254.8,3079.1
2,Ideal,4335.7,2272.9,3752.1,4756.0,3489.7,3284.6,2468.1,3250.3
3,Premium,3947.3,3856.1,4455.3,5545.9,4485.5,4550.3,2831.2,3795.1
4,Very Good,4078.2,4396.2,3932.4,4988.7,3805.4,4215.8,2459.4,3037.8

* merge: https://datadoctorblog.com/2023/05/22/Py-Basic-Pandas-Merge/

In [ ]:
df_b1 = df.iloc[:4, 4:7]
df_b2 = df.iloc[1:5, 5:8]
df_b2

In [146]:
#  pd.concat(df_b1, df_b2) # ❌❌❌❌

In [ ]:
pd.concat([df_b1, df_b2]) # 데이터프레임 객체를 리스트로 감싸는 것을 잊지 말것!!🔥🔥🔥

In [ ]:
pd.concat([df_b1, df_b2], axis = 1)

In [ ]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)