## 교육 중 작성하는 코드는 깃허브 통해서 공유 드립니다.

In [2]:
import pandas as pd

In [ ]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

In [ ]:
df_s.iloc[:2, ]

In [ ]:
df_s.loc[:2, ]

In [ ]:
df_s.v1

In [ ]:
df_s.shape

In [ ]:
df_s["shape"]

In [ ]:
df_s.iloc[:, :-1]

In [ ]:
df_s.loc[:, "v2":]

In [15]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [16]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [17]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [18]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [19]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [23]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [26]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [27]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [28]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [29]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [30]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [ ]:
df_s1 = df_s.add_prefix("pre_")
df_s1

In [32]:
df_s2 = df_s.add_suffix("_nor") # 기출유형
df_s2

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [ ]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

In [ ]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

In [43]:
df["종가"].idxmax()

117

In [44]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [45]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [63]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()

In [ ]:
df_sub.info()

In [49]:
pd.__version__

'3.0.1'

In [ ]:
df_sub.columns

In [ ]:
df_sub.count()

In [ ]:
df_sub.dtypes

In [ ]:
df_sub.isna().sum() # ⭐⭐⭐ 중요!

In [ ]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

In [ ]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

In [60]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [64]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df_sub["new1"] = df_sub["Sepal.Length"].astype("str") + "cm"
df_sub

* 정렬: https://datadoctorblog.com/2023/04/25/Py-Basic-Pandas-Sorting/
* 원소/조합세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/

In [69]:
df = pd.read_csv("bike.csv")
len(df)

10886

In [76]:
df["season"].unique()

array([1, 2, 3, 4])

In [78]:
len(df["season"].unique())

4

In [77]:
df["season"].nunique()

4

In [79]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [80]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [81]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

In [82]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [ ]:
df[["season", "holiday"]].drop_duplicates() # 중복행 제거

In [ ]:
pd.crosstab(df["season"], df["holiday"])

In [85]:
df_ck = df.loc[(df["season"] == 1) & (df["holiday"] == 1), ]
len(df_ck)

71

In [86]:
sum((df["season"] == 1) & (df["holiday"] == 1))

71

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [ ]:
df.groupby("cut")["price"].max()

In [ ]:
df_g1 = df.groupby("cut")["price"].max().reset_index()
df_g1

In [ ]:
df_g2 = df.groupby(["cut", "color"])["price"].max().reset_index()
df_g2.head(3)

In [ ]:
df_g3 = df.groupby("cut")[["price", "carat"]].max().reset_index()
df_g3.head(3)

In [ ]:
df_g4 = df.groupby("cut")["carat"].agg(["min", "max"]).reset_index()
df_g4.head(3)

In [92]:
df_g5 = df.groupby("cut")[["carat", "price"]].agg({"carat": "max", "price": "min"}).reset_index() # ⭐ 기출유형
df_g5.head(3)

     cut  carat  price
0   Fair   5.01    337
1   Good   3.01    327
2  Ideal   3.50    326

* 문자 데이터: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [110]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [94]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [95]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [ ]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

In [ ]:
df_tx["v2"].str.replace("a", "🔥")

In [ ]:
df_tx["v2"].str.replace("aaa", "🔥")

In [100]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [101]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [ ]:
df_tx.loc[df_tx["v2"].str.contains("a"), ]

In [ ]:
df_tx.loc[~df_tx["v2"].str.contains("a"), ]

In [ ]:
df_tx["v3"].str.split("-")

In [ ]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"][0]

In [ ]:
df_tx["v4"].str.split("-")

In [ ]:
df_tx["v4"].str.split("-").explode()

In [115]:
# df_tx["v4"].str.split("-").explode().reset_index()

In [117]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_3 = df_tx_v4_2.fillna("🥗")
df_tx_v4_3

   v4_0  v4_1  v4_2
0   123     🥗     🥗
1  1234  5678     🥗
2   010  1234  5678

* 시간데이터: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [118]:
ser_t1 = pd.Series(["2026-09-09", "2026-09-10", "2026-09-11"])
ser_t2 = pd.Series(["2026년 09월 09일", "2026년 09월 10일", "2026년 09월 11일"])
ser_t3 = pd.Series([20260909, 20260910, 20260911])
ser_t4 = pd.Series([1234, 2345, 3456])

In [122]:
pd.to_datetime(ser_t1)

0   2026-09-09
1   2026-09-10
2   2026-09-11
dtype: datetime64[us]

In [125]:
# pd.to_datetime(ser_t2) # 에러

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [126]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-09-09
1   2026-09-10
2   2026-09-11
dtype: datetime64[us]

In [ ]:
pd.to_datetime(ser_t3)

In [ ]:
pd.to_datetime(ser_t3.astype("str"))

In [ ]:
pd.to_datetime(ser_t4)

In [132]:
pd.to_datetime(ser_t4, origin = "2026-09-09", unit = "D")

0   2030-01-25
1   2033-02-09
2   2036-02-25
dtype: datetime64[s]

In [ ]:
df = pd.read_csv("bike.csv")
df_dt2 = df[["datetime"]].copy() # 시험장에서는 Pandas 버전이 낮아서, 깊은 복사(.copy()사용) 권장
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])

In [ ]:
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday # 토: 5
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [138]:
df_dt2.head(2)

,datetime,date,yyyymm,year,month,wday,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,2011-01-01 10:00:00

In [144]:
df_dt = pd.DataFrame(dict(date = ["2026-09-09", "2026-09-10", "2026-09-11"]))
df_dt["origin"] = "2026-12-31"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["origin"] - df_dt["date"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2026-09-09 2026-12-31 113 days     113
1 2026-09-10 2026-12-31 112 days     112
2 2026-09-11 2026-12-31 111 days     111

In [143]:
df_dt.dtypes

date       datetime64[us]
origin     datetime64[us]
diff      timedelta64[us]
diff_d              int64
dtype: object

In [145]:
import numpy as np

In [147]:
df_t = pd.DataFrame(dict(date = pd.date_range("2026-01-01", "2026-01-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(),
                            (df_t["v_s1"] + df_t["v_sn1"]) / 2, 
                            df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate()

In [149]:
df_t

        date      v   v_s1  v_sn1  v_fill_1  v_fill_2
0 2026-01-01  100.0    NaN  200.0     100.0     100.0
1 2026-01-02  200.0  100.0  300.0     200.0     200.0
2 2026-01-03  300.0  200.0    NaN     300.0     300.0
3 2026-01-04    NaN  300.0  500.0     400.0     400.0
4 2026-01-05  500.0    NaN  600.0     500.0     500.0
5 2026-01-06  600.0  500.0  700.0     600.0     600.0
6 2026-01-07  700.0  600.0    NaN     700.0     700.0

* .melt(): https://datadoctorblog.com/2023/05/07/Py-Basic-Pandas-Melt/
* pivot: https://datadoctorblog.com/2023/05/10/Py-Basic-Pandas-Pivoting/

In [155]:
df = pd.read_csv("elec_load_2017_7d.csv")
df.head(2)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330
1,2017,1,2,57067,55148,53983,53571,54027,55388,57753,...,72228,71945,72641,73387,72294,69989,67893,66504,67435,69275

In [ ]:
df_m1 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head(2)

In [ ]:
df_m2 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"], var_name = "HOUR", value_name = "LOAD")
df_m2.head(2)

In [156]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지

In [158]:
df_m2.tail()

     YEAR  MONTH  DAY   HOUR   LOAD  h1  h2  h3  h4
163  2017      1    3  X24HR  71346  24  24  24  24
164  2017      1    4  X24HR  70834  24  24  24  24
165  2017      1    5  X24HR  66687  24  24  24  24
166  2017      1    6  X24HR  63214  24  24  24  24
167  2017      1    7  X24HR  69219  24  24  24  24

In [167]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [168]:
df.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [169]:
sum(df["color"] == "E"), sum(df["price"] < 1000)

(9797, 14499)

In [170]:
df_g1 = df.groupby(["color", "cut"])["price"].mean().reset_index()
df_g1.head(2)

  color   cut        price
0     D  Fair  4291.061350
1     D  Good  3405.382175

In [171]:
df_g2 = pd.crosstab(index = df["color"], columns = df["cut"], values = df["price"],
                    aggfunc = "mean")
df_g2

cut           Fair         Good        Ideal      Premium    Very Good
color
D      4291.061350  3405.382175  2629.094566  3631.292576  3470.467284
E      3682.312500  3423.644159  2597.550090  3538.914420  3214.652083
F      3827.003205  3495.750275  3374.939362  4324.890176  3778.820240
G      4239.254777  4123.482204  3720.706388  4500.742134  3872.753806
H      5135.683168  4276.254986  3889.334831  5216.706780  4535.390351
I      4685.445714  5078.532567  4451.970377  5946.180672  5255.879568
J      4975.655462  4574.172638  4918.186384  6294.591584  5103.513274

In [172]:
df_g3 = df.pivot_table(index = "color", columns = "cut", values = "price", 
                       aggfunc = "mean")
df_g3

cut           Fair         Good        Ideal      Premium    Very Good
color
D      4291.061350  3405.382175  2629.094566  3631.292576  3470.467284
E      3682.312500  3423.644159  2597.550090  3538.914420  3214.652083
F      3827.003205  3495.750275  3374.939362  4324.890176  3778.820240
G      4239.254777  4123.482204  3720.706388  4500.742134  3872.753806
H      5135.683168  4276.254986  3889.334831  5216.706780  4535.390351
I      4685.445714  5078.532567  4451.970377  5946.180672  5255.879568
J      4975.655462  4574.172638  4918.186384  6294.591584  5103.513274

* 병합: https://datadoctorblog.com/2023/05/22/Py-Basic-Pandas-Merge/

In [174]:
df = pd.read_csv("bike.csv")
df_b1 = df.iloc[:4, 4:7]
df_b2 = df.iloc[1:5, 5:8]

In [178]:
# df_b2

In [ ]:
pd.concat([df_b1, df_b2])

In [ ]:
pd.concat([df_b1, df_b2], axis = 1)

In [ ]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)

In [194]:
df.head(2)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40

In [195]:
df2 = df[["datetime", "temp"]].copy()
df2["datetime"] = pd.to_datetime(df2["datetime"])
df2["date"] = df2["datetime"].dt.date
df2.head(2)

             datetime  temp        date
0 2011-01-01 00:00:00  9.84  2011-01-01
1 2011-01-01 01:00:00  9.02  2011-01-01

In [196]:
df2_g1 = df2.groupby("date")["temp"].max().reset_index()
df2_g1["temp2"] = df2_g1["temp"].shift(1)
df2_g1.head()

         date   temp  temp2
0  2011-01-01  18.86    NaN
1  2011-01-02  18.86  18.86
2  2011-01-03  10.66  18.86
3  2011-01-04  12.30  10.66
4  2011-01-05  12.30  12.30

In [193]:
df2_join1 = pd.merge(df2, df2_g1.drop(columns = "temp"), 
                     left_on = "date", right_on = "date",
                     how = "left")
df2_join1["temp_diff"] = df2_join1["temp"] - df2_join1["temp2"]
df2_join1.tail()

                 datetime   temp        date  temp2  temp_diff
10881 2012-12-19 19:00:00  15.58  2012-12-19   20.5      -4.92
10882 2012-12-19 20:00:00  14.76  2012-12-19   20.5      -5.74
10883 2012-12-19 21:00:00  13.94  2012-12-19   20.5      -6.56
10884 2012-12-19 22:00:00  13.94  2012-12-19   20.5      -6.56
10885 2012-12-19 23:00:00  13.12  2012-12-19   20.5      -7.38

In [198]:
df_dia = pd.read_csv("diamonds.csv")
df_dia.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [200]:
df_dia_sub1 = df_dia.loc[df_dia["clarity"].str.contains("^S"), ] # S로 시작하는 원소
df_dia_sub1["clarity"].unique()

<StringArray>
['SI2', 'SI1']
Length: 2, dtype: str

In [202]:
df_dia_sub2 = df_dia.loc[df_dia["clarity"].str.contains("[0-9]$"), ] # 숫자 한글자로 끝나는
df_dia_sub2["clarity"].unique()

<StringArray>
['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1']
Length: 7, dtype: str