### 제가 작성하는 모든 코드는 github을 통해서 공유드립니다.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))

In [3]:
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [4]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [5]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [6]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [7]:
df_s.shape

(3, 3)

In [8]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [9]:
# df_s.loc[:, "shape"]

In [10]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [11]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [12]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [13]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [14]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [15]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [16]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [17]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [18]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [19]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [20]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [21]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [22]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [23]:
df_s1 = df_s.add_prefix("aa_")
df_s1

   aa_v1  aa_v2 aa_shape
0    100    400        A
1    200    500        B
2    300    600        C

In [24]:
df_s2 = df_s.add_suffix("_nor")
df_s2

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [25]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
1,KTOP 30,11520.28,-86.30,-0.74,11609.44,11702.14,11490.84,50048566,5645660149606,1208343758559140,20210503

In [26]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
29,KRX 300,1916.40,15.35,0.81,1903.57,1916.40,1892.36,244040965,11708937073166,2043945386926060,20210504
58,KRX 300,1927.40,11.00,0.57,1916.50,1927.40,1904.76,341534594,13004811637843,2059578026871265,20210506
87,KRX 300,1936.40,9.00,0.47,1926.59,1942.80,1925.24,253210064,11101387594368,2070880919861705,20210507
116,KRX 300,1968.47,32.07,1.66,1938.63,1973.17,1938.63,294421965,13784089230905,2105851479694870,20210510
145,KRX 300,1936.37,-32.10,-1.63,1962.35,1962.35,1929.74,339313903,15976844135869,2075382637364310,20210511
174,KRX 300,1903.99,-32.38,-1.67,1936.18,1936.82,1891.55,352799341,17136393156387,2043316163563660,20210512
203,KRX 300,1878.46,-25.53,-1.34,1893.72,1899.65,1869.37,402046342,16819555547844,2014899605250130,20210513
232,KRX 300,1899.13,20.67,1.10,1884.85,1905.26,1884.85,229722051,11413338490975,2038805937109210,20210514
261,KRX 300,1891.72,-7.41,-0.39,1906.35,1912.03,1882.03,258826078,11333749894174,2027913472817160,20210517
290,KRX 300,1913.67,21.95,1.16,1892.13,1917.43,1892.13,248484463,11503457331908,2053066878361790,20210518
319,KRX 300,1906.26,-7.41,-0.39,1914.61,1914.61,1894.97,224240546,10906767355146,2047273506168110,20210520
348,KRX 300,1907.38,1.12,0.06,1912.44,1932.91,1902.03,247944350,12200080796814,2042477090377600,20210521
377,KRX 300,1897.69,-9.69,-0.51,1906.60,1910.68,1893.57,210439901,9568918143070,2035955475360540,20210524
406,KRX 300,1915.26,17.57,0.93,1903.17,1916.85,1900.82,208362193,9591985036024,2054548999380540,20210525
435,KRX 300,1911.68,-3.58,-0.19,1915.76,1922.77,1907.37,257307289,10837464472787,2051152192863740,20210526
464,KRX 300,1910.09,-1.59,-0.08,1913.55,1915.55,1894.84,327607567,17156385452981,2043966667110420,20210527
493,KRX 300,1922.87,12.78,0.67,1913.77,1929.84,1912.48,234219802,10813228145679,2058019926179550,20210528
522,KRX 300,1932.64,9.77,0.51,1924.63,1933.75,1916.75,278319769,11293303810625,2068979877957040,20210531

In [27]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [28]:
df["종가"].idxmax()

117

In [29]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [30]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

* 결측치 처리: https://datadoctorblog.com/2023/04/24/Py-Basic-Pandas-Missing/

In [31]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
df_sub.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  5 non-null      float64
 1   Sepal.Width   4 non-null      float64
 2   Petal.Length  4 non-null      float64
 3   Petal.Width   5 non-null      float64
 4   Species       5 non-null      str
dtypes: float64(4), str(1)
memory usage: 332.0 bytes

In [33]:
df_sub.dtypes # 시험버전에서는 Species가 object 로 나옴.

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species             str
dtype: object

In [34]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [35]:
df_sub.isna().sum() # 🌟🌟🌟

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [36]:
df_sub.isna().sum(axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [37]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [38]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
df_sub_bind = pd.concat([df_sub1, df_sub2])
df_sub_bind

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [41]:
df_sub.loc[:, "Sepal.Width"] = df_sub.loc[:, "Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
df_sub5 = df.tail(3)
df_sub5

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

In [43]:
df_sub5.reset_index()

   index  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0    147           6.5          3.0           5.2          2.0  virginica
1    148           6.2          3.4           5.4          2.3  virginica
2    149           5.9          3.0           5.1          NaN  virginica

In [44]:
df_sub6 = df_sub5.reset_index(drop = True)
df_sub6

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0           6.5          3.0           5.2          2.0  virginica
1           6.2          3.4           5.4          2.3  virginica
2           5.9          3.0           5.1          NaN  virginica

In [45]:
"a" + "b"

'ab'

In [46]:
# 100 + "만원"

In [47]:
df_sub6["SL2"] = df_sub6["Sepal.Length"].astype("str")
df_sub6["SL2_add"] = df_sub6["SL2"] + "cm"
df_sub6

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,SL2,SL2_add
0,6.5,3.0,5.2,2.0,virginica,6.5,6.5cm
1,6.2,3.4,5.4,2.3,virginica,6.2,6.2cm
2,5.9,3.0,5.1,NaN,virginica,5.9,5.9cm

In [48]:
df = pd.read_csv("bike.csv")
df.head(2)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40

In [49]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

* 원소/조합 세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/
* crosstab(): https://datadoctorblog.com/2023/05/06/Py-Basic-Pandas-Crosstab/

In [50]:
df["season"].unique()

array([1, 2, 3, 4])

In [51]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [52]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [53]:
df[["season", "holiday"]].drop_duplicates() # 중복행제거

      season  holiday
0          1        0
372        1        1
1323       2        0
1658       2        1
2690       3        0
2762       3        1
4055       4        0
4271       4        1

In [54]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [55]:
df_ck = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_ck)

2615

In [56]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [57]:
df = pd.read_csv("diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [58]:
df_g1 = df.groupby("cut")["depth"].max().reset_index()
df_g1

         cut  depth
0       Fair   79.0
1       Good   67.0
2      Ideal   66.7
3    Premium   63.0
4  Very Good   64.9

In [59]:
df_g2 = df.groupby(["cut", "color"])["depth"].max().reset_index()
df_g2 = df_g2.sort_values(["color", "cut"], ascending = [False, True])
df_g2.head()

          cut color  depth
6        Fair     J   73.6
13       Good     J   66.0
20      Ideal     J   65.4
27    Premium     J   63.0
34  Very Good     J   64.1

In [60]:
df_g3 = df.groupby("color")[["price", "carat"]].min().reset_index()
df_g3

  color  price  carat
0     D    357   0.20
1     E    326   0.20
2     F    342   0.20
3     G    354   0.23
4     H    337   0.23
5     I    334   0.23
6     J    335   0.23

In [61]:
df_g4 = df.groupby("color")["price"].agg(["min", "max"]).reset_index()
df_g4

  color  min    max
0     D  357  18693
1     E  326  18731
2     F  342  18791
3     G  354  18818
4     H  337  18803
5     I  334  18823
6     J  335  18710

In [62]:
df_g5 = df.groupby("color")[["price", "carat"]].agg({"price": "min",
                                                     "carat": "max"}).reset_index()
df_g5 # 🎯🎯시험 기출 전처리 유형🎯🎯

  color  price  carat
0     D    357   3.40
1     E    326   3.05
2     F    342   3.01
3     G    354   3.01
4     H    337   4.13
5     I    334   4.01
6     J    335   5.01

* 문자데이터: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [63]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300], 
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [64]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [65]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [66]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🛫"})

0    abc
1      🔥
2      🛫
Name: v2, dtype: str

In [67]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [68]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [69]:
df_tx["v2"].str.replace("a", "") # 🎯🎯

0     bc
1
2    ccc
Name: v2, dtype: str

In [70]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [71]:
df_tx["v2"].str.contains("a").sum()

np.int64(2)

In [72]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [73]:
df_tx.loc[df_tx["v2"].str.contains("a"), ]

    v1   v2         v3
0  100  abc        123
1  200  aaa  1234-5678

In [74]:
df_tx.loc[~df_tx["v2"].str.contains("a"), ]

    v1   v2             v3
2  300  ccc  010-1234-5678

In [75]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [76]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"][0], df_tx["v3"][0]

('123', 123)

In [77]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [78]:
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: str

In [79]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4

      0     1     2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [80]:
df_tx_v4_2 = df_tx_v4.fillna("🥗").add_prefix("v4_")
df_tx_v4_2

   v4_0  v4_1  v4_2
0   123     🥗     🥗
1  1234  5678     🥗
2   010  1234  5678

In [81]:
ser_t1 = pd.Series(["2026-04-08", "2026-04-09", "2026-04-10"])
ser_t2 = pd.Series(["2026년 04월 08일", "2026년 04월 09일", "2026년 04월 10일"])
ser_t3 = pd.Series([20260408, 20260409, 20260410])
ser_t4 = pd.Series([1234, 2345, 3456])

In [82]:
pd.to_datetime(ser_t1)

0   2026-04-08
1   2026-04-09
2   2026-04-10
dtype: datetime64[us]

In [83]:
# pd.to_datetime(ser_t2) # 에러!!!

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [89]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-04-08
1   2026-04-09
2   2026-04-10
dtype: datetime64[us]

In [85]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020260408
1   1970-01-01 00:00:00.020260409
2   1970-01-01 00:00:00.020260410
dtype: datetime64[ns]

In [86]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-04-08
1   2026-04-09
2   2026-04-10
dtype: datetime64[us]

In [87]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [90]:
pd.to_datetime(ser_t4, origin = "2026-04-08", unit = "D")

0   2029-08-24
1   2032-09-08
2   2035-09-24
dtype: datetime64[s]

In [92]:
df_bike = pd.read_csv("bike.csv")
df_dt2 = df_bike[["datetime"]].copy()

In [93]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0)
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [94]:
df_dt2.tail(2)

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
10884,2012-12-19 22:00:00,2012-12-19,2012-12,2012,12,2,0,22,2012-12-20 07:00:00
10885,2012-12-19 23:00:00,2012-12-19,2012-12,2012,12,2,0,23,2012-12-20 08:00:00

In [99]:
df_dt = ser_t1.to_frame(name = "date")
df_dt["origin"] = "2026-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin    diff  diff_d
0 2026-04-08 2026-01-01 97 days      97
1 2026-04-09 2026-01-01 98 days      98
2 2026-04-10 2026-01-01 99 days      99

In [106]:
df_t = pd.DataFrame(dict(date = pd.date_range("2026-04-08", "2026-04-14"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))

In [108]:
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(), 
                            (df_t["v_s1"] + df_t["v_sn1"]) / 2, 
                            df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate()

In [109]:
df_t

        date      v   v_s1  v_ns1  v_sn1  v_fill_1  v_fill_2
0 2026-04-08  100.0    NaN  200.0  200.0     100.0     100.0
1 2026-04-09  200.0  100.0  300.0  300.0     200.0     200.0
2 2026-04-10  300.0  200.0    NaN    NaN     300.0     300.0
3 2026-04-11    NaN  300.0  500.0  500.0     400.0     400.0
4 2026-04-12  500.0    NaN  600.0  600.0     500.0     500.0
5 2026-04-13  600.0  500.0  700.0  700.0     600.0     600.0
6 2026-04-14  700.0  600.0    NaN    NaN     700.0     700.0