## 제가 작성하는 모든 코드는 github을 통해 공유드릴 예정입니다.
놓쳐도 불안핑 되지 않기.

In [2]:
import numpy as np
import pandas as pd

In [6]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [7]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [8]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [9]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [10]:
df_s.shape

(3, 3)

In [11]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [12]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [ ]:
df_s.loc[:, "v2":]

In [13]:
df_s.drop(columns = "shape")

    v1   v2
0  100  400
1  200  500
2  300  600

In [14]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [15]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [16]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [18]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [21]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [22]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [25]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [26]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [28]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [29]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [30]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [32]:
df_s2 = df_s.add_prefix("p_")
df_s2

   p_v1  p_v2 p_shape
0   100   400       A
1   200   500       B
2   300   600       C

In [31]:
df_s3 = df_s.add_suffix("_nor")
df_s3

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [ ]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

In [45]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [46]:
df["종가"].idxmax()

117

In [47]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [48]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

* 결측치: https://datadoctorblog.com/2023/04/24/Py-Basic-Pandas-Missing/
* 결측치 처리1: https://datadoctorblog.com/2023/07/29/Py-Preprocessing-Missing-01/

In [ ]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

In [ ]:
df_sub.info()

In [ ]:
df_sub.dtypes # 시험버전은 str이 아닌 object로 출력됨

In [ ]:
df_sub.count()

In [60]:
df_sub.isna().sum() # 🎯🎯🎯

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64