In [1]:
import numpy as np
import pandas as pd

In [3]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [4]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [5]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [6]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [7]:
df_s.shape

(3, 3)

In [8]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [9]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [10]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [13]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [14]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [16]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [18]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [19]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [20]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [21]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [22]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [24]:
# from sklearn.metrics import 
# 자동완성은 [Tab] 활용

In [26]:
# import sklearn.metrics as sm
# dir(sm)

In [30]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [31]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [32]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [ ]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

In [ ]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

In [39]:
df["종가"].idxmax()

117

In [ ]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

In [43]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [ ]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub.info()

In [47]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [48]:
df_sub.dtypes # Pandas 3.0 이전버전은 "str"이 아닌 "object"로 표기됨.

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species             str
dtype: object

In [ ]:
df_sub.isna()

In [52]:
df_sub.isna().sum()

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [54]:
df_sub.isna().sum(axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [55]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [56]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [57]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [60]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub # Pandas 3.0 이전 버전의 경우 빨간색 경고 메세지가 출력될 수 있음.

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [64]:
df_sub2 = df.tail(3)
df_sub2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

In [ ]:
df_sub2.reset_index()

In [ ]:
df_sub2.reset_index(drop = True)

In [ ]:
df_sub2.set_index("Species")

In [70]:
df_sub3 = df_sub2.set_index("Species").reset_index()
df_sub3

     Species  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0  virginica           6.5          3.0           5.2          2.0
1  virginica           6.2          3.4           5.4          2.3
2  virginica           5.9          3.0           5.1          NaN

In [72]:
df_sub4 = df_sub3.sort_values("Sepal.Length")
df_sub4 # xxx

     Species  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
2  virginica           5.9          3.0           5.1          NaN
1  virginica           6.2          3.4           5.4          2.3
0  virginica           6.5          3.0           5.2          2.0

* 원소/조합 세기: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/

In [ ]:
df = pd.read_csv("bike.csv")
df.head(1)

In [80]:
df["season"].unique()

array([1, 2, 3, 4])

In [81]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [82]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [83]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [84]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

In [85]:
df[["season", "holiday"]].drop_duplicates()

      season  holiday
0          1        0
372        1        1
1323       2        0
1658       2        1
2690       3        0
2762       3        1
4055       4        0
4271       4        1

In [86]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [87]:
df_ck = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_ck)

2615

In [88]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [96]:
df.groupby("cut")["depth"].max()

cut
Fair         79.0
Good         67.0
Ideal        66.7
Premium      63.0
Very Good    64.9
Name: depth, dtype: float64

In [97]:
df_g1 = df.groupby("cut")["depth"].max().reset_index()
df_g1

         cut  depth
0       Fair   79.0
1       Good   67.0
2      Ideal   66.7
3    Premium   63.0
4  Very Good   64.9

In [98]:
df.groupby("cut")[["depth", "x"]].max()

           depth      x
cut
Fair        79.0  10.74
Good        67.0   9.44
Ideal       66.7   9.65
Premium     63.0  10.14
Very Good   64.9  10.01

In [99]:
ser_g2 = df.groupby(["cut", "color"])["x"].max()
ser_g2.head()

cut   color
Fair  D         9.42
      E         8.16
      F         8.58
      G         8.75
      H        10.00
Name: x, dtype: float64

In [100]:
df_g2 = df.groupby(["cut", "color"])["x"].max().reset_index()
df_g2.head()

    cut color      x
0  Fair     D   9.42
1  Fair     E   8.16
2  Fair     F   8.58
3  Fair     G   8.75
4  Fair     H  10.00

In [ ]:
df_g3 = df.groupby("cut")["y"].agg(["min", "max"]).reset_index()
df_g3

In [103]:
df_g4 = df.groupby("cut")[["x", "y"]].agg({"x": "min", "y": "max"}).reset_index() # 🎯🎯 기출유형
df_g4

         cut    x      y
0       Fair  0.0  10.54
1       Good  0.0   9.38
2      Ideal  0.0  31.80
3    Premium  0.0  58.90
4  Very Good  0.0   9.94

* 문자열 데이터 핸들링: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [ ]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

In [105]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [106]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [107]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

0    abc
1      🔥
2      🩵
Name: v2, dtype: str

In [108]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [109]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [110]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [111]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [112]:
df_tx.loc[df_tx["v2"].str.contains("a"), ]

    v1   v2         v3
0  100  abc        123
1  200  aaa  1234-5678

In [113]:
df_tx.loc[~df_tx["v2"].str.contains("a"), ]

    v1   v2             v3
2  300  ccc  010-1234-5678

In [114]:
pd.Series([True, False])

0     True
1    False
dtype: bool

In [115]:
~pd.Series([True, False])

0    False
1     True
dtype: bool

In [119]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [120]:
df_tx["v3"][0]

123

In [121]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"][0]

'123'

In [122]:
df_tx.loc[0, "v4"]

'123'

In [123]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [ ]:
df_tx["v4"].str.split("-").explode()

In [ ]:
df_tx["v4"].str.split("-").explode().reset_index()

In [ ]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4 # Pandas 3.0 이전버전은 NaN이 아닌 None으로 나옴.

In [ ]:
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_2

In [ ]:
df_tx_v4_3 = df_tx_v4_2.fillna("🥗")
df_tx_v4_3

* 시간데이터 처리: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [144]:
ser_t1 = pd.Series(["2026-05-27", "2026-05-28", "2026-05-29"])
ser_t2 = pd.Series(["2026년 05월 27일", "2026년 05월 28일", "2026년 05월 29일"])
ser_t3 = pd.Series([20260527, 20260528, 20260529])
ser_t4 = pd.Series([1234, 2345, 3456])

In [ ]:
pd.to_datetime(ser_t1)

In [147]:
# pd.to_datetime(ser_t2) # 에러남!

* https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [148]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-05-27
1   2026-05-28
2   2026-05-29
dtype: datetime64[us]

In [149]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020260527
1   1970-01-01 00:00:00.020260528
2   1970-01-01 00:00:00.020260529
dtype: datetime64[ns]

In [150]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-05-27
1   2026-05-28
2   2026-05-29
dtype: datetime64[us]

In [151]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [152]:
pd.to_datetime(ser_t4, origin = "2026-05-27", unit = "D")

0   2029-10-12
1   2032-10-27
2   2035-11-12
dtype: datetime64[s]

In [ ]:
df = pd.read_csv("bike.csv")
df_dt2 = df[["datetime"]].copy() 
# 시험버전의 Pandas는 얕은 복사가 되는 경우가 많기 때문에
# 간간히 .copy()로 깊은 복사를 하는 것이 좋음.
df_dt2.head(2)

In [160]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])

In [166]:
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 유형 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday # 토: 5, 일: 6
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0) # 주말: 1, 주중: 0
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [170]:
df_dt2.head(2)

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,1,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,1,2011-01-01 10:00:00

In [168]:
# print(df_dt2["datetime"].dt.strftime.__doc__)

In [172]:
df_dt = pd.DataFrame(dict(date = ["2026-05-27", "2026-05-28", "2026-05-29"]))
df_dt["origin"] = "2026-01-01"
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["date"] = pd.to_datetime(df_dt["date"])
df_dt["diff"] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2026-05-27 2026-01-01 146 days     146
1 2026-05-28 2026-01-01 147 days     147
2 2026-05-29 2026-01-01 148 days     148

In [ ]:
df_dt.dtypes

In [ ]:
# df_dt["diff"] + 100
df_dt["diff"] / 2

In [178]:
df_t = pd.DataFrame(dict(date = pd.date_range("2026-01-01", "2026-01-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))

In [ ]:
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_s2"] = df_t["v"].shift(2)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(), 
                            (df_t["v_s1"] + df_t["v_sn1"]) / 2,
                            df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate() # 보간법

In [182]:
df_t

        date      v   v_s1   v_s2  v_sn1  v_fill_1  v_fill_2
0 2026-01-01  100.0    NaN    NaN  200.0     100.0     100.0
1 2026-01-02  200.0  100.0    NaN  300.0     200.0     200.0
2 2026-01-03  300.0  200.0  100.0    NaN     300.0     300.0
3 2026-01-04    NaN  300.0  200.0  500.0     400.0     400.0
4 2026-01-05  500.0    NaN  300.0  600.0     500.0     500.0
5 2026-01-06  600.0  500.0    NaN  700.0     600.0     600.0
6 2026-01-07  700.0  600.0  500.0    NaN     700.0     700.0

* .melt(): https://datadoctorblog.com/2023/05/07/Py-Basic-Pandas-Melt/

In [ ]:
df = pd.read_csv("elec_load_2017_7d.csv")
df.head(1)

In [ ]:
df_m1 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head(1)

In [ ]:
df_m2 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"],
                var_name = "HOUR", value_name = "LOAD")
df_m2.head(2)

In [187]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지
# regex는 regular expression(정규 표현식)

In [188]:
df_m2.tail(3)

     YEAR  MONTH  DAY   HOUR   LOAD  h1  h2  h3  h4
165  2017      1    5  X24HR  66687  24  24  24  24
166  2017      1    6  X24HR  63214  24  24  24  24
167  2017      1    7  X24HR  69219  24  24  24  24

In [191]:
df = pd.read_csv("diamonds.csv")
df.head(1)

   carat    cut color clarity  depth  table  price     x     y     z
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

In [ ]:
df_agg1 = df.pivot_table(index = "color", columns = "cut",
                         values = "carat", aggfunc = "min").reset_index()
df_agg1

In [ ]:
df_agg2 = df.groupby(["color", "cut"])["carat"].min().reset_index()
df_agg2.head()

In [198]:
df_agg3 = pd.crosstab(index = df["color"], columns = df["cut"], 
                      values = df["carat"], aggfunc = "min").reset_index()
df_agg3

cut color  Fair  Good  Ideal  Premium  Very Good
0       D  0.25  0.23   0.20     0.20       0.23
1       E  0.22  0.23   0.20     0.20       0.20
2       F  0.25  0.23   0.23     0.20       0.23
3       G  0.23  0.23   0.23     0.23       0.23
4       H  0.33  0.25   0.23     0.23       0.23
5       I  0.41  0.30   0.23     0.23       0.24
6       J  0.30  0.28   0.23     0.30       0.24

In [203]:
df_bike = pd.read_csv("bike.csv")
df_b1 = df_bike.iloc[:4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8]

In [205]:
df_b2

   temp   atemp  humidity
1  9.02  13.635        80
2  9.02  13.635        80
3  9.84  14.395        75
4  9.84  14.395        75

In [ ]:
# pd.concat(df_b1, df_b2) # error!!
pd.concat([df_b1, df_b2])

In [ ]:
pd.concat([df_b1, df_b2], axis = 1)

In [210]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)

   weather  temp   atemp  temp_y  atemp_y  humidity_y
0        1  9.84  14.395    9.02   13.635          80
1        1  9.02  13.635    9.02   13.635          80
2        1  9.02  13.635    9.84   14.395          75
3        1  9.84  14.395    9.84   14.395          75