### 코드는 깃헙 저장소를 통해서 모두 공유 드립니다.

In [1]:
import numpy as np
import pandas as pd

In [5]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [6]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [7]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [8]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [9]:
df_s.shape

(3, 3)

In [10]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [11]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [12]:
df_s.loc[:, "v2":]

    v2 shape
0  400     A
1  500     B
2  600     C

In [16]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [17]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [18]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [19]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [20]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [21]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [22]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [23]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [24]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [27]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [28]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [29]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

,지수명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,날짜
0,KRX 300,1901.05,-11.63,-0.61,1913.15,1929.94,1896.65,279548840,13488481375036,2028800954161500,20210503
1,KTOP 30,11520.28,-86.30,-0.74,11609.44,11702.14,11490.84,50048566,5645660149606,1208343758559140,20210503

In [34]:
# df_sub = df.loc[df["지수명"] == "KRX 300", ]
# df_sub

In [ ]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

In [37]:
df["종가"].idxmax()

117

In [ ]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

In [ ]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

* 결측 처리: https://datadoctorblog.com/2023/04/24/Py-Basic-Pandas-Missing/
* https://datadoctorblog.com/2023/07/29/Py-Preprocessing-Missing-01/
* https://datadoctorblog.com/2023/09/22/Py-Preprocessing-Missing-02/
* https://datadoctorblog.com/2024/09/19/Py-Preprocessing-Missing-03/

In [ ]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

In [43]:
df_sub.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  5 non-null      float64
 1   Sepal.Width   4 non-null      float64
 2   Petal.Length  4 non-null      float64
 3   Petal.Width   5 non-null      float64
 4   Species       5 non-null      str
dtypes: float64(4), str(1)
memory usage: 332.0 bytes

In [47]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [48]:
df_sub.isna()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0         False         True          True        False    False
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False

In [49]:
df_sub.isna().sum() # 🌟

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [50]:
df_sub.isna().sum(axis = 1)

0    2
1    0
2    0
3    0
4    0
dtype: int64

In [51]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [52]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [53]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [54]:
ser_na = pd.Series([100, np.nan, np.nan, 400])
ser_na

0    100.0
1      NaN
2      NaN
3    400.0
dtype: float64

In [ ]:
ser_na.fillna(0)

In [60]:
# ser_na.fillna(method = "ffill")
ser_na.ffill()

0    100.0
1    100.0
2    100.0
3    400.0
dtype: float64

In [59]:
ser_na.bfill()

0    100.0
1    400.0
2    400.0
3    400.0
dtype: float64

In [61]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df_ck = df.loc[df["Sepal.Length"] > 7.5, ]
df_ck

In [72]:
df_ck1 = df_ck.reset_index()
df_ck1

   index  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0    105           7.6          3.0           6.6          2.1  virginica
1    117           7.7          3.8           6.7          2.2  virginica
2    118           7.7          2.6           6.9          2.3  virginica
3    122           7.7          NaN           6.7          2.0  virginica
4    131           7.9          3.8           6.4          2.0  virginica
5    135           7.7          3.0           6.1          2.3  virginica

In [73]:
df_ck2 = df_ck.reset_index(drop = True)
df_ck2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0           7.6          3.0           6.6          2.1  virginica
1           7.7          3.8           6.7          2.2  virginica
2           7.7          2.6           6.9          2.3  virginica
3           7.7          NaN           6.7          2.0  virginica
4           7.9          3.8           6.4          2.0  virginica
5           7.7          3.0           6.1          2.3  virginica

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [75]:
ser_cnt = df["cut"].value_counts()
ser_cnt

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [76]:
ser_cnt.sort_index()

cut
Fair          1610
Good          4906
Ideal        21551
Premium      13791
Very Good    12082
Name: count, dtype: int64

* 원소/조합: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/

In [ ]:
df = pd.read_csv("bike.csv")
df.head(2)

In [81]:
df["season"].unique()

array([1, 2, 3, 4])

In [82]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [83]:
df["season"].nunique()

4

In [84]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [85]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [ ]:
df[["season", "holiday"]].drop_duplicates() # 중복행 제거

In [87]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [88]:
df_ck = df.loc[(df["season"] == 1) & (df["holiday"] == 0), ]
len(df_ck)

2615

In [89]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

* crosstab(): https://datadoctorblog.com/2023/05/06/Py-Basic-Pandas-Crosstab/
* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(1)

In [94]:
df.groupby("cut")["price"].max()

cut
Fair         18574
Good         18788
Ideal        18806
Premium      18823
Very Good    18818
Name: price, dtype: int64

In [95]:
df_g1 = df.groupby("cut")["price"].max().reset_index()
df_g1

         cut  price
0       Fair  18574
1       Good  18788
2      Ideal  18806
3    Premium  18823
4  Very Good  18818

In [96]:
df.groupby("cut")["price"].agg(["min", "max"])

           min    max
cut
Fair       337  18574
Good       327  18788
Ideal      326  18806
Premium    326  18823
Very Good  336  18818

In [97]:
df_g2 = df.groupby(["cut", "color"])["price"].max().reset_index()
df_g2.head(2)

    cut color  price
0  Fair     D  16386
1  Fair     E  15584

In [98]:
df_g3 = df.groupby("cut")[["price", "carat"]].min().reset_index()
df_g3.head(2)

    cut  price  carat
0  Fair    337   0.22
1  Good    327   0.23

In [100]:
df_g4 = df.groupby("cut")[["price", "carat"]].agg({"price": "max",
                                                   "carat": "min"}).reset_index()
df_g4.head(3) # 🎯시험 기출 유형🎯

     cut  price  carat
0   Fair  18574   0.22
1   Good  18788   0.23
2  Ideal  18806   0.20

* 문자데이터: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [ ]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300], 
                          v2 = ["abc", "aaa", "ccc"], 
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

In [105]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [106]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [107]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

0    abc
1      🔥
2      🩵
Name: v2, dtype: str

In [108]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [109]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [110]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [111]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [113]:
df_tx.loc[df_tx["v2"].str.contains("a"), ]

    v1   v2         v3
0  100  abc        123
1  200  aaa  1234-5678

In [114]:
df_tx.loc[~df_tx["v2"].str.contains("a"), ]

    v1   v2             v3
2  300  ccc  010-1234-5678

In [117]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [118]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"][0]

'123'

In [119]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [120]:
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: str

In [121]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4

      0     1     2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [122]:
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_2

   v4_0  v4_1  v4_2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [123]:
df_tx2 = pd.concat([df_tx, df_tx_v4_2], axis = 1)
df_tx2

    v1   v2             v3             v4  v4_0  v4_1  v4_2
0  100  abc            123            123   123   NaN   NaN
1  200  aaa      1234-5678      1234-5678  1234  5678   NaN
2  300  ccc  010-1234-5678  010-1234-5678   010  1234  5678

* 시간 데이터: https://datadoctorblog.com/2023/04/14/Py-Basic-Pandas-Time-Data/

In [128]:
ser_t1 = pd.Series(["2026-05-13", "2026-05-14", "2026-05-15"])
ser_t2 = pd.Series(["2026년 05월 13일", "2026년 05월 14일", "2026년 05월 15일"])
ser_t3 = pd.Series([20260513, 20260514, 20260515])
ser_t4 = pd.Series([1234, 2345, 3456])

In [132]:
pd.to_datetime(ser_t1)

0   2026-05-13
1   2026-05-14
2   2026-05-15
dtype: datetime64[us]

In [134]:
# pd.to_datetime(ser_t2) # 에러!!!

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [135]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-05-13
1   2026-05-14
2   2026-05-15
dtype: datetime64[us]

In [136]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020260513
1   1970-01-01 00:00:00.020260514
2   1970-01-01 00:00:00.020260515
dtype: datetime64[ns]

In [137]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-05-13
1   2026-05-14
2   2026-05-15
dtype: datetime64[us]

In [138]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [139]:
pd.to_datetime(ser_t4, origin = "2026-05-13", unit = "D")

0   2029-09-28
1   2032-10-13
2   2035-10-29
dtype: datetime64[s]

In [ ]:
df = pd.read_csv("bike.csv")
df_dt2 = df[["datetime"]].copy() 
# 시험버전의 pandas의 경우 얕은 복사가 되는 경우가 많기 때문에
# 단순 필터링이나 특정 변수를 뽑아내고자 하는 경우 .copy()로 깊은 복사를 실시하는 것이 안전.
df_dt2.head(2)

In [142]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"  ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"] = df_dt2["datetime"].dt.strftime("%Y-%m") # 기출 🎯
df_dt2["year"  ] = df_dt2["datetime"].dt.year
df_dt2["month" ] = df_dt2["datetime"].dt.month
df_dt2["wday"  ] = df_dt2["datetime"].dt.weekday # 토: 5, 일: 6
df_dt2["wend"  ] = np.where(df_dt2["wday"] >= 5, 1, 0) # 주말 1, 주중 0
df_dt2["hour"  ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [143]:
df_dt2.head(2)

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,1,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,1,2011-01-01 10:00:00

In [155]:
df_dt2.dtypes

datetime    datetime64[us]
date                object
yyyymm                 str
year                 int32
month                int32
wday                 int32
wend                 int64
hour                 int32
dt_s9h      datetime64[us]
dtype: object

In [ ]:
# [shift] + [tab] 이 동작하지 않을 경우.
# 메서드/함수/클래스 뒤에 괄호를 쓰지 않고 .__doc__ 를 이어서 쓰면서 print() 함수와 함께 쓰면
# 해당 문서를 출력할 수 있음.
print(df.loc[df["season"] == 1, "temp"].max.__doc__)

In [150]:
# dir(pd.Series)
# from sklearn.metrics import 
import sklearn.metrics as sm
dir(sm)

In [153]:
# [m for m in dir(sm) if m[0] != "_"]

In [157]:
df_dt = pd.DataFrame(dict(date = ["2077-08-01", "2077-08-02", "2077-08-03"]))
df_dt["origin"] = "2077-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2077-08-01 2077-01-01 212 days     212
1 2077-08-02 2077-01-01 213 days     213
2 2077-08-03 2077-01-01 214 days     214

In [ ]:
df_t = pd.DataFrame(dict(date = pd.date_range("2024-01-01", "2024-01-07"),
                         v = [100, 200, 300, np.nan, 500, 600, 700]))
df_t

In [161]:
df_t["v_s1"] = df_t["v"].shift(1)
df_t["v_sn1"] = df_t["v"].shift(-1)
df_t["v_fill_1"] = np.where(df_t["v"].isna(),
                            (df_t["v_s1"] + df_t["v_sn1"]) / 2,
                            df_t["v"])
df_t["v_fill_2"] = df_t["v"].interpolate()

In [163]:
df_t

        date      v   v_s1  v_sn1  v_fill_1  v_fill_2
0 2024-01-01  100.0    NaN  200.0     100.0     100.0
1 2024-01-02  200.0  100.0  300.0     200.0     200.0
2 2024-01-03  300.0  200.0    NaN     300.0     300.0
3 2024-01-04    NaN  300.0  500.0     400.0     400.0
4 2024-01-05  500.0    NaN  600.0     500.0     500.0
5 2024-01-06  600.0  500.0  700.0     600.0     600.0
6 2024-01-07  700.0  600.0    NaN     700.0     700.0

* .melt(): https://datadoctorblog.com/2023/05/07/Py-Basic-Pandas-Melt/

In [164]:
df = pd.read_csv("elec_load_2017_7d.csv")
df.head(1)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330

In [168]:
df_m1 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head(2)

   YEAR  MONTH  DAY variable  value
0  2017      1    1     X1HR  60178
1  2017      1    2     X1HR  57067

In [169]:
df_m2 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"], 
                var_name = "HOUR", value_name = "LOAD")
df_m2.head(2)

   YEAR  MONTH  DAY  HOUR   LOAD
0  2017      1    1  X1HR  60178
1  2017      1    2  X1HR  57067

In [170]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
# regex: regular expression, 정규표현식, 텍스트 처리를 위한 특수 문법
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지

In [172]:
df_m2.tail()

     YEAR  MONTH  DAY   HOUR   LOAD  h1  h2  h3  h4
163  2017      1    3  X24HR  71346  24  24  24  24
164  2017      1    4  X24HR  70834  24  24  24  24
165  2017      1    5  X24HR  66687  24  24  24  24
166  2017      1    6  X24HR  63214  24  24  24  24
167  2017      1    7  X24HR  69219  24  24  24  24

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [179]:
df_g1 = df.groupby(["cut", "color"])["price"].min().reset_index()
df_g1.head(2)

    cut color  price
0  Fair     D    536
1  Fair     E    337

In [180]:
df_g2 = pd.crosstab(index   = df["cut"], 
                    columns = df["color"],
                    values  = df["price"],
                    aggfunc = "min")
df_g2

color        D    E    F    G    H    I    J
cut
Fair       536  337  496  369  659  735  416
Good       361  327  357  394  368  351  335
Ideal      367  326  408  361  357  348  340
Premium    367  326  342  382  368  334  363
Very Good  357  352  357  354  337  336  336

In [181]:
df_g3 = df.pivot_table(index = "cut", columns = "color", 
                       values = "price", aggfunc = "min")
df_g3

color        D    E    F    G    H    I    J
cut
Fair       536  337  496  369  659  735  416
Good       361  327  357  394  368  351  335
Ideal      367  326  408  361  357  348  340
Premium    367  326  342  382  368  334  363
Very Good  357  352  357  354  337  336  336

In [ ]:
df_bike = pd.read_csv("bike.csv")
df_bike.head(1)

In [ ]:
df_b1 = df_bike.iloc[:4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8]
df_b1

In [ ]:
df_b2

In [191]:
pd.concat([df_b1, df_b2])

   weather  temp   atemp  humidity
0      1.0  9.84  14.395       NaN
1      1.0  9.02  13.635       NaN
2      1.0  9.02  13.635       NaN
3      1.0  9.84  14.395       NaN
1      NaN  9.02  13.635      80.0
2      NaN  9.02  13.635      80.0
3      NaN  9.84  14.395      75.0
4      NaN  9.84  14.395      75.0

In [189]:
pd.concat([df_b1, df_b2], axis = 1)

   weather  temp   atemp  temp   atemp  humidity
0      1.0  9.84  14.395   NaN     NaN       NaN
1      1.0  9.02  13.635  9.02  13.635      80.0
2      1.0  9.02  13.635  9.02  13.635      80.0
3      1.0  9.84  14.395  9.84  14.395      75.0
4      NaN   NaN     NaN  9.84  14.395      75.0

In [192]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")],
          axis = 1)

   weather  temp   atemp  temp_y  atemp_y  humidity_y
0        1  9.84  14.395    9.02   13.635          80
1        1  9.02  13.635    9.02   13.635          80
2        1  9.02  13.635    9.84   14.395          75
3        1  9.84  14.395    9.84   14.395          75

In [193]:
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [194]:
df_g1 = df.groupby("cut")["price"].mean().reset_index()
df_g2 = df.groupby("cut")["table"].mean().reset_index()
df_g1.head(2)

    cut        price
0  Fair  4358.757764
1  Good  3928.864452

In [ ]:
df_g_join = pd.merge(df_g1,           df_g2, 
                     left_on = "cut", right_on = "cut",
                     how = "inner")
df_g_join

In [196]:
df_g_join = pd.merge(df_g1, df_g2, on = "cut", how = "inner")
df_g_join

         cut        price      table
0       Fair  4358.757764  59.053789
1       Good  3928.864452  58.694639
2      Ideal  3457.541970  55.951668
3    Premium  4584.257704  58.746095
4  Very Good  3981.759891  57.956150