## 제가 작성하는 모든 코드는 github을 통해 공유드릴 예정입니다.
놓쳐도 불안핑 되지 않기.

In [2]:
import numpy as np
import pandas as pd

In [6]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = [400, 500, 600],
                         shape = ["A", "B", "C"]))
df_s

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [7]:
df_s.iloc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B

In [8]:
df_s.loc[:2, ]

    v1   v2 shape
0  100  400     A
1  200  500     B
2  300  600     C

In [9]:
df_s.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [10]:
df_s.shape

(3, 3)

In [11]:
df_s["shape"]

0    A
1    B
2    C
Name: shape, dtype: str

In [12]:
df_s.iloc[:, :-1]

    v1   v2
0  100  400
1  200  500
2  300  600

In [ ]:
df_s.loc[:, "v2":]

In [13]:
df_s.drop(columns = "shape")

    v1   v2
0  100  400
1  200  500
2  300  600

In [14]:
df_s.loc[df_s["v1"] == 200, ]

    v1   v2 shape
1  200  500     B

In [15]:
df_s.loc[df_s["v1"] != 200, ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [16]:
df_s["v1"] == 200

0    False
1     True
2    False
Name: v1, dtype: bool

In [18]:
~(df_s["v1"] == 200)

0     True
1    False
2     True
Name: v1, dtype: bool

In [21]:
df_s.loc[~(df_s["v1"] == 200), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [22]:
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]

Empty DataFrame
Columns: [v1, v2, shape]
Index: []

In [25]:
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

    v1   v2 shape
1  200  500     B
2  300  600     C

In [26]:
condi_1 = df_s["v1"] == 200
condi_2 = df_s["v2"] == 500
df_s.loc[condi_1 & condi_2, ]

    v1   v2 shape
1  200  500     B

In [28]:
df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [29]:
df_s.loc[df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
0  100  400     A
2  300  600     C

In [30]:
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

    v1   v2 shape
1  200  500     B

In [32]:
df_s2 = df_s.add_prefix("p_")
df_s2

   p_v1  p_v2 p_shape
0   100   400       A
1   200   500       B
2   300   600       C

In [31]:
df_s3 = df_s.add_suffix("_nor")
df_s3

   v1_nor  v2_nor shape_nor
0     100     400         A
1     200     500         B
2     300     600         C

In [ ]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

In [45]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [46]:
df["종가"].idxmax()

117

In [47]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [48]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

         지수명        종가        날짜
117  KTOP 30  11869.29  20210510

* 결측치: https://datadoctorblog.com/2023/04/24/Py-Basic-Pandas-Missing/
* 결측치 처리1: https://datadoctorblog.com/2023/07/29/Py-Preprocessing-Missing-01/

In [ ]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

In [ ]:
df_sub.info()

In [ ]:
df_sub.dtypes # 시험버전은 str이 아닌 object로 출력됨

In [ ]:
df_sub.count()

In [60]:
df_sub.isna().sum() # 🎯🎯🎯

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [61]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [62]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [63]:
df_sub3 = df_sub.dropna()
df_sub3

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [64]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [68]:
df_sub_ck = df_sub.set_index("Species").reset_index()
df_sub_ck

  Species  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0  setosa           5.1       -999.0           1.4          0.2
1  setosa           4.9          3.0           1.4          0.2
2  setosa           4.7          3.2           1.3          0.2
3  setosa           4.6          3.1           1.5          0.2
4  setosa           5.0          3.6           1.4          0.2

* 정렬: https://datadoctorblog.com/2023/04/25/Py-Basic-Pandas-Sorting/
* 범주형 변수 탐색: https://datadoctorblog.com/2023/04/04/Py-Basic-Pandas-Counting/

In [ ]:
df = pd.read_csv("bike.csv")
df.head(2)

In [75]:
df["season"].unique()

array([1, 2, 3, 4])

In [76]:
df["season"].nunique()

4

In [77]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [78]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [79]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [80]:
df["season"].value_counts().sort_index()

season
1    2686
2    2733
3    2733
4    2734
Name: count, dtype: int64

In [ ]:
df[["season", "holiday"]].drop_duplicates()

In [84]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [83]:
df_ck1 = df.loc[(df["season"] == 1) & (df["holiday"] == 1), ]
len(df_ck1)

71

* .groupby(): https://datadoctorblog.com/2023/04/28/Py-Basic-Pandas-Groupby/

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [88]:
df.groupby("cut")["carat"].max()

cut
Fair         5.01
Good         3.01
Ideal        3.50
Premium      4.01
Very Good    4.00
Name: carat, dtype: float64

In [89]:
df_g1 = df.groupby("cut")["price"].max().reset_index()
df_g1

         cut  price
0       Fair  18574
1       Good  18788
2      Ideal  18806
3    Premium  18823
4  Very Good  18818

In [101]:
# ser_ck = df.groupby(["cut", "color"])["carat"].mean()
# ser_ck.xs("Fair") # .xs() 는 알 필요 없음.

In [102]:
df_g2 = df.groupby(["cut", "color"])["carat"].mean().reset_index()
df_g2.head()

    cut color     carat
0  Fair     D  0.920123
1  Fair     E  0.856607
2  Fair     F  0.904712
3  Fair     G  1.023822
4  Fair     H  1.219175

In [ ]:
df_g3 = df.groupby("cut")[["carat", "price"]].mean().reset_index()
df_g3.head()

In [ ]:
df_g4 = df.groupby("cut")["price"].agg(["min", "max"]).reset_index()
df_g4.head()

In [93]:
df_g5 = df.groupby("cut")[["carat", "price"]].agg({"carat": "min", "price": "max"}).reset_index()
df_g5.head() # ⭐시험기출유형⭐

         cut  carat  price
0       Fair   0.22  18574
1       Good   0.23  18788
2      Ideal   0.20  18806
3    Premium   0.20  18823
4  Very Good   0.20  18818

* 문자열 처리: https://datadoctorblog.com/2023/04/20/Py-Basic-Pandas-String-Data/

In [132]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                          v2 = ["abc", "aaa", "ccc"],
                          v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [133]:
df_tx["v2"].replace("a", "🔥")

0    abc
1    aaa
2    ccc
Name: v2, dtype: str

In [134]:
df_tx["v2"].replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [135]:
df_tx["v2"].replace({"aaa": "🔥", "ccc": "🩵"})

0    abc
1      🔥
2      🩵
Name: v2, dtype: str

In [136]:
df_tx["v2"].str.replace("a", "🔥")

0    🔥bc
1    🔥🔥🔥
2    ccc
Name: v2, dtype: str

In [137]:
df_tx["v2"].str.replace("aaa", "🔥")

0    abc
1      🔥
2    ccc
Name: v2, dtype: str

In [138]:
df_tx["v2"].str.contains("a")

0     True
1     True
2    False
Name: v2, dtype: bool

In [139]:
~df_tx["v2"].str.contains("a")

0    False
1    False
2     True
Name: v2, dtype: bool

In [140]:
df_tx["new1"] = df_tx["v2"].str.replace("a", "🔥")
df_tx["v2"] = df_tx["v2"].str.replace("a", "🔥")
df_tx

    v1   v2             v3 new1
0  100  🔥bc            123  🔥bc
1  200  🔥🔥🔥      1234-5678  🔥🔥🔥
2  300  ccc  010-1234-5678  ccc

In [141]:
df_tx["v3"].str.split("-")

0                  NaN
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v3, dtype: object

In [142]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"][0]

'123'

In [143]:
df_tx["v3"][0]

123

In [144]:
df_tx

    v1   v2             v3 new1             v4
0  100  🔥bc            123  🔥bc            123
1  200  🔥🔥🔥      1234-5678  🔥🔥🔥      1234-5678
2  300  ccc  010-1234-5678  ccc  010-1234-5678

In [145]:
df_tx["v4"].str.split("-")

0                [123]
1         [1234, 5678]
2    [010, 1234, 5678]
Name: v4, dtype: object

In [146]:
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: str

In [147]:
df_tx_v4 = df_tx["v4"].str.split("-", expand = True)
df_tx_v4

      0     1     2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [148]:
df_tx_v4_2 = df_tx_v4.add_prefix("v4_")
df_tx_v4_2

   v4_0  v4_1  v4_2
0   123   NaN   NaN
1  1234  5678   NaN
2   010  1234  5678

In [149]:
df_tx_v4_3 = df_tx_v4_2.fillna("🥗")
df_tx_v4_3

   v4_0  v4_1  v4_2
0   123     🥗     🥗
1  1234  5678     🥗
2   010  1234  5678

In [150]:
ser_t1 = pd.Series(["2026-09-16", "2026-09-17", "2026-09-18"])
ser_t2 = pd.Series(["2026년 09월 16일", "2026년 09월 17일", "2026년 09월 18일"])
ser_t3 = pd.Series([20260916, 20260917, 20260918])
ser_t4 = pd.Series([1234, 2345, 3456])

In [153]:
pd.to_datetime(ser_t1)

0   2026-09-16
1   2026-09-17
2   2026-09-18
dtype: datetime64[us]

In [155]:
# pd.to_datetime(ser_t2) # 에러 발생

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [156]:
pd.to_datetime(ser_t2, format = "%Y년 %m월 %d일")

0   2026-09-16
1   2026-09-17
2   2026-09-18
dtype: datetime64[us]

In [157]:
pd.to_datetime(ser_t3)

0   1970-01-01 00:00:00.020260916
1   1970-01-01 00:00:00.020260917
2   1970-01-01 00:00:00.020260918
dtype: datetime64[ns]

In [158]:
pd.to_datetime(ser_t3.astype("str"))

0   2026-09-16
1   2026-09-17
2   2026-09-18
dtype: datetime64[us]

In [159]:
pd.to_datetime(ser_t4)

0   1970-01-01 00:00:00.000001234
1   1970-01-01 00:00:00.000002345
2   1970-01-01 00:00:00.000003456
dtype: datetime64[ns]

In [160]:
pd.to_datetime(ser_t4, origin = "2026-09-16", unit = "D")

0   2030-02-01
1   2033-02-16
2   2036-03-03
dtype: datetime64[s]

In [162]:
df = pd.read_csv("bike.csv")
df_dt2 = df[["datetime"]].copy() 
# 시험에는 Pandas가 깊은 복사를 종종 지원하지 않아 안전하게 필터링 시 (간간히).copy() 사용 권장.

In [163]:
df_dt2["datetime"] = pd.to_datetime(df_dt2["datetime"])
df_dt2["date"    ] = df_dt2["datetime"].dt.date
df_dt2["yyyymm"  ] = df_dt2["datetime"].dt.strftime("%Y-%m")
df_dt2["year"    ] = df_dt2["datetime"].dt.year
df_dt2["month"   ] = df_dt2["datetime"].dt.month
df_dt2["wday"    ] = df_dt2["datetime"].dt.weekday
df_dt2["wend"    ] = np.where(df_dt2["wday"] >= 5, 1, 0)
df_dt2["hour"    ] = df_dt2["datetime"].dt.hour
df_dt2["dt_s9h"  ] = df_dt2["datetime"] + pd.to_timedelta(9, unit = "h")

In [164]:
df_dt2.head()

,datetime,date,yyyymm,year,month,wday,wend,hour,dt_s9h
0,2011-01-01 00:00:00,2011-01-01,2011-01,2011,1,5,1,0,2011-01-01 09:00:00
1,2011-01-01 01:00:00,2011-01-01,2011-01,2011,1,5,1,1,2011-01-01 10:00:00
2,2011-01-01 02:00:00,2011-01-01,2011-01,2011,1,5,1,2,2011-01-01 11:00:00
3,2011-01-01 03:00:00,2011-01-01,2011-01,2011,1,5,1,3,2011-01-01 12:00:00
4,2011-01-01 04:00:00,2011-01-01,2011-01,2011,1,5,1,4,2011-01-01 13:00:00

In [166]:
df_dt = pd.DataFrame(dict(date = ["2077-08-01", "2077-08-02", "2077-08-03"]))
df_dt["origin"] = "2077-01-01"
df_dt["date"  ] = pd.to_datetime(df_dt["date"])
df_dt["origin"] = pd.to_datetime(df_dt["origin"])
df_dt["diff"  ] = df_dt["date"] - df_dt["origin"]
df_dt["diff_d"] = df_dt["diff"].dt.days
df_dt

        date     origin     diff  diff_d
0 2077-08-01 2077-01-01 212 days     212
1 2077-08-02 2077-01-01 213 days     213
2 2077-08-03 2077-01-01 214 days     214

In [167]:
df_dt.dtypes

date       datetime64[us]
origin     datetime64[us]
diff      timedelta64[us]
diff_d              int64
dtype: object

In [170]:
df_dt = pd.DataFrame(dict(date = pd.date_range("2026-01-01", "2026-01-07"),
                          v = [100, 200, 300, np.nan, 500, 600, 700]))
df_dt["v_s1"] = df_dt["v"].shift(1)
df_dt["v_sn1"] = df_dt["v"].shift(-1)
df_dt["v_fill_1"] = np.where(df_dt["v"].isna(),
                             (df_dt["v_s1"] + df_dt["v_sn1"]) / 2,
                             df_dt["v"])
df_dt["v_fill_2"] = df_dt["v"].interpolate()

In [171]:
df_dt

        date      v   v_s1  v_sn1  v_fill_1  v_fill_2
0 2026-01-01  100.0    NaN  200.0     100.0     100.0
1 2026-01-02  200.0  100.0  300.0     200.0     200.0
2 2026-01-03  300.0  200.0    NaN     300.0     300.0
3 2026-01-04    NaN  300.0  500.0     400.0     400.0
4 2026-01-05  500.0    NaN  600.0     500.0     500.0
5 2026-01-06  600.0  500.0  700.0     600.0     600.0
6 2026-01-07  700.0  600.0    NaN     700.0     700.0

* .melt(): https://datadoctorblog.com/2023/05/07/Py-Basic-Pandas-Melt/

In [179]:
df = pd.read_csv("elec_load_2017_7d.csv")
df.head(2)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330
1,2017,1,2,57067,55148,53983,53571,54027,55388,57753,...,72228,71945,72641,73387,72294,69989,67893,66504,67435,69275

In [180]:
df_m1 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1.head()

   YEAR  MONTH  DAY variable  value
0  2017      1    1     X1HR  60178
1  2017      1    2     X1HR  57067
2  2017      1    3     X1HR  66263
3  2017      1    4     X1HR  68403
4  2017      1    5     X1HR  68053

In [ ]:
df_m2 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"], var_name = "HOUR", value_name = "LOAD")
df_m2.head()

In [189]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex = True) # X 또는 HR
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex = True) # 영문 대문자
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex = True) # 숫자를 제외한 나머지
df_m2["h5"] = df_m2["HOUR"].str.extract("([0-9]{1,2})") # 숫자 1~2자리 최초 매칭분 추출.

In [190]:
df_m2.head(2)

   YEAR  MONTH  DAY  HOUR   LOAD h1 h2 h3 h4 h5
0  2017      1    1  X1HR  60178  1  1  1  1  1
1  2017      1    2  X1HR  57067  1  1  1  1  1

In [ ]:
df = pd.read_csv("diamonds.csv")
df.head(2)

In [ ]:
pd.crosstab(index = df["cut"], columns = df["color"], values = df["price"],
            aggfunc = "min")

In [ ]:
df.groupby(["cut", "color"])["price"].min()

* pivoting: https://datadoctorblog.com/2023/05/10/Py-Basic-Pandas-Pivoting/

In [196]:
df.pivot_table(index = "cut", columns = "color", values = "price", aggfunc = "min")

color        D    E    F    G    H    I    J
cut
Fair       536  337  496  369  659  735  416
Good       361  327  357  394  368  351  335
Ideal      367  326  408  361  357  348  340
Premium    367  326  342  382  368  334  363
Very Good  357  352  357  354  337  336  336

* 병합: https://datadoctorblog.com/2023/05/22/Py-Basic-Pandas-Merge/

In [199]:
df_bike = pd.read_csv("bike.csv")

In [202]:
df_b1 = df_bike.iloc[:4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8]

In [204]:
df_b2

   temp   atemp  humidity
1  9.02  13.635        80
2  9.02  13.635        80
3  9.84  14.395        75
4  9.84  14.395        75

In [ ]:
pd.concat([df_b1, df_b2])

In [210]:
pd.concat([df_b1, df_b2], axis = 1)

   weather  temp   atemp  temp   atemp  humidity
0      1.0  9.84  14.395   NaN     NaN       NaN
1      1.0  9.02  13.635  9.02  13.635      80.0
2      1.0  9.02  13.635  9.02  13.635      80.0
3      1.0  9.84  14.395  9.84  14.395      75.0
4      NaN   NaN     NaN  9.84  14.395      75.0

In [209]:
pd.concat([df_b1, df_b2.reset_index(drop = True).add_suffix("_y")], axis = 1)

   weather  temp   atemp  temp_y  atemp_y  humidity_y
0        1  9.84  14.395    9.02   13.635          80
1        1  9.02  13.635    9.02   13.635          80
2        1  9.02  13.635    9.84   14.395          75
3        1  9.84  14.395    9.84   14.395          75

In [221]:
# 11년도 요일별 count의 평균
# 12년도 요일별 count의 평균
# 하나로 합치고 비교해볼까?
df_q = df_bike[["datetime", "count"]].copy()
df_q.head(2)

              datetime  count
0  2011-01-01 00:00:00     16
1  2011-01-01 01:00:00     40

In [222]:
df_q["datetime"] = pd.to_datetime(df_q["datetime"])
df_q["year"] = df_q["datetime"].dt.year
df_q["wday"] = df_q["datetime"].dt.weekday
df_q.head(2)

             datetime  count  year  wday
0 2011-01-01 00:00:00     16  2011     5
1 2011-01-01 01:00:00     40  2011     5

In [223]:
df_y11 = df_q.loc[df_q["year"] == 2011, ]
df_y12 = df_q.loc[df_q["year"] == 2012, ]
len(df_y11), len(df_y12)

(5422, 5464)

In [ ]:
df_y11_g = df_y11.groupby("wday")["count"].mean().reset_index()
df_y12_g = df_y12.groupby("wday")["count"].mean().reset_index()
df_y11_g = df_y11_g.rename(columns = {"count": "cnt_11"})
df_y12_g = df_y12_g.rename(columns = {"count": "cnt_12"})
df_y11_g.head(2)

In [230]:
df_g_join1 = pd.merge(df_y11_g, df_y12_g, on = "wday", how = "inner")
df_g_join1["diff"] = df_g_join1["cnt_12"] - df_g_join1["cnt_11"]
df_g_join1["ratio"] = df_g_join1["cnt_12"] / df_g_join1["cnt_11"]
df_g_join1

   wday      cnt_11      cnt_12        diff     ratio
0     0  151.989501  227.477820   75.488319  1.496668
1     1  144.693402  235.165796   90.472394  1.625270
2     2  129.069737  245.427307  116.357570  1.901509
3     3  142.280840  250.294564  108.013724  1.759159
4     4  151.870064  246.352151   94.482087  1.622124
5     5  143.502451  253.151042  109.648591  1.764089
6     6  145.926702  213.568098   67.641397  1.463530

In [233]:
df_q.head(2)

             datetime  count  year  wday
0 2011-01-01 00:00:00     16  2011     5
1 2011-01-01 01:00:00     40  2011     5

In [240]:
df_q_p = df_q.pivot_table(index = "wday", columns = "year",
                          values = "count", aggfunc = "mean").add_prefix("y").reset_index()
df_q_p["diff"] = df_q_p["y2012"] - df_q_p["y2011"]
df_q_p

year  wday       y2011       y2012        diff
0        0  151.989501  227.477820   75.488319
1        1  144.693402  235.165796   90.472394
2        2  129.069737  245.427307  116.357570
3        3  142.280840  250.294564  108.013724
4        4  151.870064  246.352151   94.482087
5        5  143.502451  253.151042  109.648591
6        6  145.926702  213.568098   67.641397